"""Machine-readable FastCFD capability registry."""

from __future__ import annotations

from typing import Any

from .registry import CASE_REGISTRY, COLLISION_REGISTRY, LATTICE_REGISTRY


CAPABILITY_REGISTRY: dict[str, Any] = {
    "backend": "fastcfd",
    "status": "foundation",
    "role": "low-cost preliminary CFD prediction and physics-screening layer before high-fidelity Fluent validation",
    "validation_gates": {
        "semantic_scene_compiler": {
            "status": "implemented",
            "checks": ["case template", "domain size", "cell length", "required zones", "boundary semantics", "obstacle clearance"],
            "entrypoint": "fromcad2cfd fastcfd compile-scene",
        },
        "physics_passport": {
            "status": "implemented",
            "checks": ["density", "viscosity", "Re", "tau/RT", "omega", "lattice Mach", "cell count", "step cadence"],
            "entrypoint": "fromcad2cfd fastcfd validate-job",
        },
        "prediction_report": {
            "status": "implemented",
            "checks": ["physics regime", "expected flow behavior", "numerical trace quality", "design implications", "parameter suggestions"],
            "entrypoint": "fromcad2cfd fastcfd predict-from-output",
        },
        "bounded_parameter_screening": {
            "status": "implemented",
            "checks": ["finite variant count", "velocity sensitivity", "cell-length sensitivity", "physics passport per variant", "ranked candidate list"],
            "entrypoint": "fromcad2cfd fastcfd screen-parameters",
        },
        "vof_physics_passport": {
            "status": "implemented_u15_vof",
            "checks": [
                "two-phase model registry",
                "phase density and viscosity",
                "initial volume-fraction closure",
                "surface tension",
                "gravity vector",
                "reference velocity",
                "time step",
                "VOF Courant number",
                "Reynolds number",
                "Weber number",
                "Bond number",
                "Capillary number",
                "Froude number",
                "fail-closed blocking errors",
            ],
            "entrypoint": "fromcad2cfd fastcfd validate-vof",
        },
        "vof_fluent_setup_hints": {
            "status": "implemented_u15_vof",
            "checks": [
                "transient VOF recommendation",
                "interface capturing recommendation",
                "time-step recommendation",
                "mesh refinement recommendation",
                "monitoring recommendation",
                "explicit no-solver-result boundary",
            ],
            "entrypoint": "fromcad2cfd fastcfd validate-vof",
        },
        "turbulence_passport": {
            "status": "implemented_u16",
            "checks": [
                "Reynolds number",
                "flow-regime classification",
                "model intent",
                "hydraulic diameter",
                "turbulence intensity",
                "estimated first-cell y-plus",
                "near-wall target range",
                "Fluent setup hints",
                "explicit no-solver-result boundary",
            ],
            "entrypoint": "fromcad2cfd fastcfd validate-turbulence",
        },
        "non_newtonian_rheology_passport": {
            "status": "implemented_u17",
            "checks": [
                "Newtonian, power-law, and Carreau-Yasuda material models",
                "shear-rate sample range",
                "apparent-viscosity curve",
                "shear stress curve",
                "finite positive viscosity",
                "shear-thinning or shear-thickening trend",
                "Fluent material setup hints",
                "explicit no-solver-result boundary",
            ],
            "entrypoint": "fromcad2cfd fastcfd run-rheology-benchmark",
        },
        "unstructured_mesh_gateway": {
            "status": "implemented_u0_u3",
            "checks": [
                "Gmsh v4 ASCII",
                "physical names",
                "owner-neighbour topology",
                "mesh quality",
                "finite-volume geometry operators",
                "VTU preview",
                "fail-closed reports",
            ],
            "entrypoint": "fromcad2cfd fastcfd unstructured inspect-mesh",
        },
        "flow_pack_adapter": {
            "status": "implemented_m4",
            "checks": [
                "CaseSpec v3 validation",
                "boundary-condition contract validation",
                "material contract validation",
                "Mesh Gateway v2 evidence attachment",
                "setup-only readiness gate",
                "agent next-action list",
                "setup-only EvidenceBundle v3 export",
                "explicit no-solver-execution boundary",
            ],
            "entrypoint": "fromcad2cfd fastcfd flow-pack build-demo",
        },
        "route_selector": {
            "status": "implemented_m5",
            "checks": [
                "Flow Pack readiness inspection",
                "case type and mesh source routing",
                "setup repair routing",
                "mesh-gateway completion routing",
                "structured native FastFluent route recommendation",
                "unstructured FVM evidence route recommendation",
                "physics-passport route recommendation",
                "Fluent planning preview route recommendation",
                "explicit no-selector-execution boundary",
            ],
            "entrypoint": "fromcad2cfd fastcfd route-selector select <flow_pack_dir>",
        },
        "route_plan_compiler": {
            "status": "implemented_m6",
            "checks": [
                "route selection ingestion",
                "pre-execution route plan artifact",
                "approval gate artifact",
                "structured FastFluent job scaffold materialization",
                "physics passport generation without solver execution",
                "safe LBM starter scaling policy",
                "commands-after-approval separation",
                "explicit no-compiler-execution boundary",
            ],
            "entrypoint": "fromcad2cfd fastcfd route-plan compile <route_selection>",
        },
        "execution_gate": {
            "status": "implemented_m7",
            "checks": [
                "route plan validation",
                "approval gate inspection",
                "materialized job audit",
                "physics passport revalidation",
                "FastFluent source preflight",
                "dry-run execution ledger",
                "runbook generation",
                "commands-after-approval preservation",
                "explicit no-gate-execution boundary",
            ],
            "entrypoint": "fromcad2cfd fastcfd execution-gate audit <route_plan>",
        },
        "controlled_runner": {
            "status": "implemented_m8",
            "checks": [
                "execution gate ingestion",
                "controlled command ledger generation",
                "dry-run execution transcript",
                "explicit approval id support for mock backend",
                "deterministic mock backend route",
                "real FastFluent execution blocked in v1",
                "Fluent launch blocked in v1",
                "arbitrary code execution blocked",
            ],
            "entrypoint": "fromcad2cfd fastcfd controlled-runner run <execution_gate>",
        },
        "result_pack_compiler": {
            "status": "implemented_s5_native_unified",
            "checks": [
                "controlled-run validation",
                "artifact index compilation",
                "agent handoff artifact",
                "decision brief generation",
                "no-solver-evidence labeling",
                "mock workflow fixture labeling",
                "advisory native evidence boundary",
                "native result adapter",
                "passed/warning/failed quality preservation",
                "screening-only warning handoff",
                "explicit non-final-CFD-validation boundary",
            ],
            "entrypoint": "fromcad2cfd fastcfd result-pack compile <controlled_run>",
        },
        "transport_coupling_core": {
            "status": "implemented_s6_unified_transport",
            "checks": [
                "transport case schema",
                "alpha, temperature, species, particle concentration, and wax-fraction demo declarations",
                "generated public mesh route",
                "provided mesh route",
                "explicit finite-volume advection",
                "explicit diffusion",
                "constant and linear-relaxation source terms",
                "bounded scalar clipping audit",
                "Courant and diffusion-number gates",
                "integral balance QoI",
                "material property coupling ranges",
                "VTU/CSV/JSON/Markdown artifacts",
                "S5 native Result Pack compatibility",
                "explicit non-final-Fluent-validation boundary",
            ],
            "entrypoint": "fromcad2cfd fastcfd transport demo --output-dir <dir>",
        },
        "workflow_runner": {
            "status": "implemented_s7_full_workflow",
            "checks": [
                "CaseSpec ingestion",
                "Flow Pack build and validation",
                "Route Selector orchestration",
                "Route Plan compilation",
                "Execution Gate audit",
                "Controlled Runner dry-run ledger",
                "S6 native advisory route",
                "Result Pack compilation",
                "stage status artifact",
                "agent decision artifact",
                "failure-stage stop behavior",
                "explicit no-Fluent-launch boundary",
            ],
            "entrypoint": "fromcad2cfd fastcfd workflow run --case-file <case.json> --output-dir <dir>",
        },
        "solver_capability_matrix": {
            "status": "implemented_solver_expansion_m0",
            "checks": [
                "native solver inventory",
                "physics coverage classification",
                "mesh support classification",
                "validation evidence classification",
                "workflow boundary declaration",
                "priority next-step declaration",
            ],
            "entrypoint": "fromcad2cfd fastcfd solver-capability-matrix",
        },
        "motion_contract_preflight": {
            "status": "implemented_motion_m0",
            "checks": [
                "kinematic motion schema",
                "moving boundary target",
                "moving obstacle target",
                "moving body target",
                "constant and sinusoidal translation",
                "constant and oscillatory rotation",
                "dangerous executable key rejection",
                "time-sampled CSV evidence",
                "explicit no-dynamic-mesh boundary",
            ],
            "entrypoint": "fromcad2cfd fastcfd motion sample <motion_file>",
        },
        "motion_mesh_adapter": {
            "status": "implemented_motion_m1",
            "checks": [
                "Gmsh mesh import",
                "motion target patch binding",
                "boundary node and element inventory",
                "mesh characteristic length estimation",
                "motion Courant warning gate",
                "motion Courant blocking gate",
                "solver adapter JSON",
                "explicit no-mesh-deformation boundary",
            ],
            "entrypoint": "fromcad2cfd fastcfd motion adapt-mesh <motion_file> <mesh_file>",
        },
        "motion_solver_preflight": {
            "status": "implemented_motion_m2",
            "checks": [
                "motion adapter status gate",
                "binding status gate",
                "active motion detection",
                "static-grid motion evidence mode",
                "dynamic-mesh request blocking",
                "run-case dispatch integration",
                "solver decision Markdown report",
            ],
            "entrypoint": "fromcad2cfd fastcfd motion solver-preflight <motion_adapter.json>",
        },
        "quasi_steady_motion_evidence": {
            "status": "implemented_motion_m3",
            "checks": [
                "motion solver preflight consumption",
                "static-grid snapshot sequence",
                "motion sample to snapshot mapping",
                "per-snapshot steady run",
                "time-series QoI CSV",
                "explicit no-dynamic-mesh boundary",
            ],
            "entrypoint": "fromcad2cfd fastcfd motion quasi-steady <case.json> <motion_adapter.json>",
        },
        "moving_obstacle_motion_evidence": {
            "status": "implemented_motion_m4",
            "checks": [
                "public obstacle-channel mesh generation",
                "obstacle_wall motion binding",
                "obstacle mesh evidence",
                "quasi-steady moving-obstacle sequence",
                "no private device geometry",
                "explicit no-immersed-boundary-solve boundary",
            ],
            "entrypoint": "fromcad2cfd fastcfd motion moving-obstacle-demo",
        },
        "unstructured_scalar_diffusion": {
            "status": "implemented_u4_u5_u30",
            "checks": [
                "mesh quality gate",
                "finite-volume geometry gate",
                "manufactured solution",
                "2D triangle and 3D tetra P1 simplex assembly",
                "CSR linear-system assembly",
                "controlled dense/sparse solver selection",
                "Dirichlet boundary values",
                "residual history",
                "solution VTU",
                "QoI error metrics",
            ],
            "entrypoint": "fromcad2cfd fastcfd unstructured solve-diffusion",
        },
        "unstructured_tetra_diffusion_smoke": {
            "status": "implemented_u30",
            "checks": [
                "public unit-cube tetra mesh generation",
                "six named surface patches",
                "fluid volume region preservation",
                "positive tetra volumes",
                "3D finite-volume face geometry",
                "P1 tetra scalar diffusion assembly",
                "one unconstrained interior node",
                "linear manufactured solution",
                "CSR linear-system solve",
                "VTU mesh and solution previews",
                "explicit no-3D-Navier-Stokes boundary",
            ],
            "entrypoint": "fromcad2cfd fastcfd unstructured solve-tetra-diffusion",
        },
        "unstructured_linear_system": {
            "status": "implemented_u5",
            "checks": [
                "CSR sparse matrix storage",
                "matrix-vector product",
                "dense direct reference solver",
                "sparse conjugate-gradient solver",
                "residual convergence metadata",
                "dense/sparse equivalence tests",
            ],
            "entrypoint": "fromcad2cfd fastcfd unstructured solve-diffusion --linear-solver sparse-cg",
        },
        "unstructured_stokes_momentum": {
            "status": "implemented_u6",
            "checks": [
                "mesh quality gate",
                "finite-volume geometry gate",
                "manufactured pressure gradient",
                "two velocity-component CSR systems",
                "controlled dense/sparse solver selection",
                "velocity error metrics",
                "cell divergence metrics",
                "solution VTU",
                "QoI report",
            ],
            "entrypoint": "fromcad2cfd fastcfd unstructured solve-stokes",
        },
        "unstructured_pressure_projection": {
            "status": "implemented_u7",
            "checks": [
                "mesh quality gate",
                "finite-volume geometry gate",
                "manufactured pressure-correction Poisson solve",
                "controlled dense/sparse solver selection",
                "predicted velocity divergence",
                "corrected velocity divergence",
                "divergence reduction ratio",
                "pressure-correction VTU",
                "QoI report",
            ],
            "entrypoint": "fromcad2cfd fastcfd unstructured solve-projection",
        },
        "unstructured_boundary_contract": {
            "status": "implemented_u9",
            "checks": [
                "required named patches",
                "boundary zone counts",
                "supported boundary-condition kinds",
                "missing condition definitions",
                "fail-closed execution block",
            ],
            "entrypoint": "fromcad2cfd fastcfd unstructured solve-flow-benchmark",
        },
        "unstructured_iterative_flow_benchmark": {
            "status": "implemented_u8_u10_u11",
            "checks": [
                "mesh quality gate",
                "boundary-condition contract gate",
                "iterative pressure-correction solves",
                "predicted divergence history",
                "corrected divergence history",
                "velocity update history",
                "flow QoI report",
                "flow VTU output",
            ],
            "entrypoint": "fromcad2cfd fastcfd unstructured solve-flow-benchmark",
        },
        "unstructured_channel_validation": {
            "status": "implemented_u12_u13",
            "checks": [
                "mesh quality gate",
                "boundary-condition contract gate",
                "parabolic inlet velocity profile",
                "outlet pressure reference",
                "wall no-slip condition",
                "pressure-drop driven Poiseuille profile",
                "velocity profile error metrics",
                "cell divergence metrics",
                "mass-balance flux proxy",
                "solution VTU output",
            ],
            "entrypoint": "fromcad2cfd fastcfd unstructured solve-channel-validation",
        },
        "unstructured_channel_convergence": {
            "status": "implemented_u14",
            "checks": [
                "generated public synthetic mesh levels",
                "repeated channel validation cases",
                "cell-center velocity L2 error trend",
                "observed order estimate",
                "per-level artifacts",
                "convergence report",
            ],
            "entrypoint": "fromcad2cfd fastcfd unstructured solve-channel-convergence",
        },
        "unstructured_obstacle_channel_evidence": {
            "status": "implemented_u18",
            "checks": [
                "public synthetic body-fitted obstacle-channel mesh",
                "inlet, outlet, wall, obstacle_wall, and fluid zone preservation",
                "mesh quality gate",
                "boundary-condition contract gate",
                "obstacle blockage ratio",
                "clearance metrics",
                "VTU preview",
                "Fluent setup hints",
                "no private geometry",
            ],
            "entrypoint": "fromcad2cfd fastcfd unstructured solve-obstacle-channel",
        },
        "vof_lite_alpha_transport": {
            "status": "implemented_u19",
            "checks": [
                "bounded alpha transport",
                "VOF-lite Courant number",
                "phase-volume balance",
                "min/max volume fraction",
                "history CSV",
                "VTU alpha preview",
                "Fluent VOF monitor hints",
                "explicit no-pressure-momentum-solver boundary",
            ],
            "entrypoint": "fromcad2cfd fastcfd unstructured solve-vof-lite",
        },
        "unstructured_turbulent_channel_solve": {
            "status": "implemented_u21",
            "checks": [
                "public synthetic channel mesh generation",
                "mesh quality gate",
                "boundary-condition contract gate",
                "Prandtl mixing-length algebraic eddy-viscosity closure",
                "iterative effective-viscosity momentum solve",
                "turbulent viscosity ratio field",
                "velocity update convergence history",
                "VTU velocity and turbulent-viscosity preview",
                "Fluent turbulence setup hints",
                "explicit simplified-RANS benchmark boundary",
            ],
            "entrypoint": "fromcad2cfd fastcfd unstructured solve-turbulent-channel",
        },
        "unstructured_kepsilon_channel_solve": {
            "status": "implemented_u22",
            "checks": [
                "public synthetic channel mesh generation",
                "mesh quality gate",
                "boundary-condition contract gate",
                "standard k-epsilon two-equation closure constants",
                "streamwise momentum solve",
                "k transport reaction-diffusion solve",
                "epsilon transport reaction-diffusion solve",
                "eddy-viscosity update from k and epsilon",
                "positive k and epsilon fields",
                "turbulence production field",
                "iteration history",
                "VTU velocity, k, epsilon, turbulent-viscosity, and production preview",
                "Fluent turbulence setup hints",
                "explicit bounded benchmark boundary",
            ],
            "entrypoint": "fromcad2cfd fastcfd unstructured solve-kepsilon-channel",
        },
        "unstructured_pressure_corrected_kepsilon_channel": {
            "status": "implemented_u23",
            "checks": [
                "public synthetic channel mesh generation",
                "mesh quality gate",
                "boundary-condition contract gate",
                "streamwise momentum prediction",
                "pressure-correction Poisson solve",
                "velocity correction and wall reapplication",
                "k transport reaction-diffusion solve",
                "epsilon transport reaction-diffusion solve",
                "eddy-viscosity update from k and epsilon",
                "positive finite k and epsilon fields",
                "turbulence production field",
                "divergence monitor history",
                "VTU velocity, pressure-correction, k, epsilon, turbulent-viscosity, and production preview",
                "Fluent pressure-velocity and turbulence setup hints",
                "explicit bounded pressure-correction benchmark boundary",
            ],
            "entrypoint": "fromcad2cfd fastcfd unstructured solve-kepsilon-pressure-channel",
        },
        "unstructured_sst_channel_solve": {
            "status": "implemented_u25",
            "checks": [
                "public synthetic channel mesh generation",
                "mesh quality gate",
                "boundary-condition contract gate",
                "Menter k-omega SST standard constants",
                "SST F1 and F2 blending functions",
                "SST eddy-viscosity limiter",
                "streamwise momentum solve",
                "k transport reaction-diffusion solve",
                "omega transport reaction-diffusion solve",
                "positive finite k and omega fields",
                "turbulence production field",
                "iteration history",
                "VTU velocity, k, omega, turbulent-viscosity, production, F1, and F2 preview",
                "Fluent SST setup hints",
                "explicit bounded benchmark boundary",
            ],
            "entrypoint": "fromcad2cfd fastcfd unstructured solve-sst-channel",
        },
        "unstructured_turbulence_ladder": {
            "status": "implemented_u24_u25",
            "checks": [
                "shared public synthetic channel mesh",
                "algebraic eddy-viscosity benchmark execution",
                "standard k-epsilon benchmark execution",
                "pressure-corrected k-epsilon benchmark execution",
                "Menter k-omega SST benchmark execution",
                "per-tier artifact preservation",
                "per-tier QoI summary",
                "recommended evidence tier",
                "explicit no-production-validation boundary",
            ],
            "entrypoint": "fromcad2cfd fastcfd unstructured solve-turbulence-ladder",
        },
        "unstructured_case_runner": {
            "status": "implemented_u26",
            "checks": [
                "agent-safe JSON case schema",
                "relative mesh path resolution",
                "normalized case artifact",
                "boundary-condition map parsing",
                "steady_incompressible solver dispatch",
                "unsupported solver family fail-closed behavior",
                "case status artifact",
            ],
            "entrypoint": "fromcad2cfd fastcfd unstructured run-case",
        },
        "unstructured_boundary_condition_schema": {
            "status": "implemented_u27",
            "checks": [
                "velocity_inlet parameter validation",
                "pressure_outlet and pressure_reference validation",
                "mass_flow_inlet parameter validation",
                "opening parameter validation",
                "symmetry parameter validation",
                "legacy benchmark boundary-kind compatibility",
                "unsupported boundary kind fail-closed behavior",
            ],
            "entrypoint": "fromcad2cfd fastcfd unstructured run-case",
        },
        "unstructured_steady_incompressible_solver": {
            "status": "implemented_s4_hardened",
            "checks": [
                "mesh quality gate",
                "boundary-condition contract gate",
                "velocity-component linear systems",
                "pressure outlet/reference pressure-correction anchoring",
                "natural pressure-correction handling on non-reference boundaries",
                "velocity boundary preservation",
                "cell divergence diagnostics",
                "boundary mass-flux balance diagnostics",
                "passed/warning/failed hardening summary",
                "agent next-action decision",
                "VTU velocity and pressure-correction preview",
                "explicit controlled-solver boundary",
            ],
            "entrypoint": "fromcad2cfd fastcfd unstructured solve-steady-incompressible",
        },
        "unstructured_public_benchmark_suite": {
            "status": "implemented_u29",
            "checks": [
                "public Poiseuille channel validation",
                "public JSON steady incompressible case",
                "public body-fitted obstacle-channel evidence",
                "public VOF-lite alpha transport",
                "public turbulence ladder",
                "per-case artifact preservation",
                "suite summary JSON and Markdown report",
                "no private geometry",
            ],
            "entrypoint": "fromcad2cfd fastcfd unstructured run-benchmark-suite",
        },
        "native_simulation_validation_pack": {
            "status": "implemented_s1",
            "checks": [
                "schema-versioned native simulation result contract",
                "structured backend status recording without fabricated outputs",
                "public unstructured FVM simulation cases",
                "Poiseuille grid-convergence evidence",
                "steady incompressible channel field output",
                "VOF-lite alpha transport field output",
                "turbulence ladder closure comparison",
                "scalar diffusion field-output smoke benchmark",
                "simulation manifest and summary report",
                "passport-to-simulation alignment reports",
                "explicit no-Fluent-launch boundary",
            ],
            "entrypoint": "fromcad2cfd fastcfd native-simulation-validation-pack-demo",
        },
        "practical_native_function_pack": {
            "status": "implemented_s2",
            "checks": [
                "schema-versioned practical native result contract",
                "1D explicit heat diffusion with Fourier-number stability check",
                "2D explicit heat diffusion with Fo_x + Fo_y stability check",
                "1D scalar advection-diffusion with CFL and diffusion-number checks",
                "bounded scalar clamp comparison",
                "Arrhenius material-property field evaluator",
                "bounded source-term ramp/clamp toy model",
                "parameter sweep with risk map and recommended time-step table",
                "wax application demo combining heat diffusion, viscosity field, source controls, and sweep evidence",
                "CSV/JSON/Markdown artifact generation",
                "explicit no-Fluent-launch boundary",
            ],
            "entrypoint": "fromcad2cfd fastcfd practical-native-demo-pack",
        },
        "practical_native_setup_pack": {
            "status": "implemented_s3",
            "checks": [
                "public-safe 1D line geometry manifest",
                "public-safe 2D channel geometry manifest with obstacle zone tagging",
                "boundary-zone counts and boundary-condition contract validation",
                "initial temperature field CSV",
                "initial scalar field CSV",
                "initial velocity field CSV",
                "S2-compatible heat, scalar, and wax case templates",
                "setup manifest and Markdown summary",
                "explicit no-Fluent-launch boundary",
            ],
            "entrypoint": "fromcad2cfd fastcfd practical-native-setup-demo",
        },
        "structured_fastfluent_backend_status": {
            "status": "implemented_s1_status_only",
            "checks": [
                "cavity2d backend status record",
                "channel2d velocity/grid backend status record",
                "obstacle2d shape-comparison backend status record",
                "no fake field output when backend is not run",
            ],
            "entrypoint": "fromcad2cfd fastcfd native-simulation-validation-pack-demo",
        },
        "unstructured_fvm_simulation_pack": {
            "status": "implemented_s1",
            "checks": [
                "Poiseuille convergence case",
                "steady incompressible channel case",
                "body-fitted obstacle evidence case",
                "VOF-lite alpha transport case",
                "turbulence ladder case",
                "scalar diffusion field smoke case",
            ],
            "entrypoint": "fromcad2cfd fastcfd native-simulation-validation-pack-demo",
        },
        "vof_lite_alpha_transport_simulation": {
            "status": "implemented_s1",
            "checks": [
                "alpha min/max history",
                "alpha mass balance",
                "Courant-number evidence",
                "VTU alpha preview",
            ],
            "entrypoint": "fromcad2cfd fastcfd native-simulation-validation-pack-demo",
        },
        "turbulence_ladder_simulation": {
            "status": "implemented_s1",
            "checks": [
                "algebraic eddy-viscosity route",
                "standard k-epsilon route",
                "pressure-corrected k-epsilon route",
                "Menter SST route",
                "model-comparison summary",
            ],
            "entrypoint": "fromcad2cfd fastcfd native-simulation-validation-pack-demo",
        },
        "passport_simulation_alignment": {
            "status": "implemented_s1",
            "checks": [
                "VOF passport to VOF-lite alignment",
                "turbulence passport to turbulence-ladder alignment",
                "rheology simulation gap report",
                "steam-air v2 simulation gap report",
                "solid-liquid simulation gap report",
            ],
            "entrypoint": "fromcad2cfd fastcfd native-simulation-validation-pack-demo",
        },
        "fluent_hint_compiler": {
            "status": "implemented_u20",
            "checks": [
                "JSON evidence artifact ingestion",
                "schema summary",
                "hint evidence requirement",
                "source artifact traceability",
                "fail-closed missing evidence checks",
                "compiled Fluent setup hint report",
                "no Fluent case editing",
            ],
            "entrypoint": "fromcad2cfd fastcfd compile-fluent-hints",
        },
        "steam_air_condensation_passport": {
            "status": "implemented_overnight_20260622",
            "checks": [
                "steam-air species fraction closure",
                "bounded saturation-temperature estimate",
                "wall condensation driving potential",
                "non-condensable gas risk",
                "near-wall thermal penetration depth",
                "initial time-step recommendation",
                "source-term stiffness risk",
                "Fluent setup hints",
                "fail-closed dangerous-key rejection",
            ],
            "entrypoint": "fromcad2cfd fastcfd validate-steam-air-condensation",
        },
        "solver_plan_patch_contract": {
            "status": "implemented_overnight_20260622",
            "checks": [
                "schema-versioned patch artifact",
                "allowlisted patch paths",
                "allowlisted patch operations",
                "evidence references for physics, numerics, transient, monitor, and source-term patches",
                "dangerous-key rejection",
                "JSON and Markdown report writers",
            ],
            "entrypoint": "fromcad2cfd fastcfd compile-fluent-patch",
        },
        "fluent_patch_compiler": {
            "status": "implemented_overnight_20260622",
            "checks": [
                "steam-air passport ingestion",
                "evidence preservation",
                "non-executing Fluent-facing patch generation",
                "monitor patch generation",
                "source-term control patch generation",
                "patch merge conflict handling",
            ],
            "entrypoint": "fromcad2cfd fastcfd compile-fluent-patch",
        },
        "vof_to_solver_plan_patch": {
            "status": "implemented_h1",
            "checks": [
                "existing VOF passport ingestion",
                "dimensionless group evidence preservation",
                "VOF transient and multiphase setup patch generation",
                "volume-fraction, Courant, and phase-mass monitor patches",
                "no Fluent launch or case editing",
            ],
            "entrypoint": "fromcad2cfd fastcfd compile-fluent-patch",
        },
        "turbulence_to_solver_plan_patch": {
            "status": "implemented_h1",
            "checks": [
                "existing turbulence passport ingestion",
                "Reynolds-regime and y-plus evidence preservation",
                "review-required handling for transitional regimes",
                "wall y-plus and wall-shear monitor patches",
                "no Fluent launch or case editing",
            ],
            "entrypoint": "fromcad2cfd fastcfd compile-fluent-patch",
        },
        "rheology_to_solver_plan_patch": {
            "status": "implemented_h1",
            "checks": [
                "existing rheology passport ingestion",
                "viscosity model and viscosity-range evidence preservation",
                "material property model patch generation",
                "viscosity monitor and output patches",
                "no UDF generation, Fluent launch, or case editing",
            ],
            "entrypoint": "fromcad2cfd fastcfd compile-fluent-patch",
        },
        "existing_passport_patch_demo": {
            "status": "implemented_h1",
            "checks": [
                "public VOF passport demo to solver-plan patch",
                "public turbulence passport demo to solver-plan patch",
                "public rheology passport demo to solver-plan patch",
                "combined patch merge with evidence preservation",
                "conflict summary artifact",
            ],
            "entrypoint": "fromcad2cfd fastcfd existing-passport-patch-demo",
        },
        "steam_air_handoff_demo": {
            "status": "implemented_overnight_20260622",
            "checks": [
                "public synthetic case writer",
                "passport and Fluent hint generation",
                "solver-plan patch compilation",
                "JSON artifact chain",
                "Markdown handoff reports",
                "no Fluent launch",
            ],
            "entrypoint": "fromcad2cfd fastcfd steam-air-handoff-demo",
        },
        "steam_air_condensation_v2": {
            "status": "implemented_h2",
            "checks": [
                "v2 steam-air condensation schemas",
                "Reynolds, Prandtl, Peclet, Jakob, and Stefan numbers",
                "Nusselt, HTC, heat-flux, and heat-transfer-rate estimates",
                "Schmidt, Sherwood, mass-transfer coefficient, and non-condensable resistance estimates",
                "source-term dimension, sign, latent-heat consistency, and stiffness checks",
                "expanded non-executing solver-plan patch recommendations",
                "no Fluent launch, UDF generation, or case editing",
            ],
            "entrypoint": "fromcad2cfd fastcfd steam-air-v2-demo",
        },
        "solid_liquid_suspension_passport": {
            "status": "implemented_h3",
            "checks": [
                "solid-liquid suspension case, passport, and Fluent hints schemas",
                "particle Reynolds number and drag-regime classification",
                "particle relaxation time and Stokes number",
                "settling velocity and residence-time comparison",
                "solid volume-fraction and particle mass-loading regimes",
                "cell-particle ratio and particle time-step risk",
                "DPM, Mixture, Eulerian multiphase, and Eulerian granular review recommendations",
                "solver-plan patch integration with monitor and acceptance criteria",
                "no Fluent launch, particle tracking solver, DEM coupling, or UDF generation",
            ],
            "entrypoint": "fromcad2cfd fastcfd solid-liquid-handoff-demo",
        },
        "wax_rheology_phase_change_passport": {
            "status": "implemented_h4",
            "checks": [
                "wax rheology / phase-change case schema",
                "Arrhenius viscosity and activation-energy calculation",
                "temperature-dependent viscosity range and ratio",
                "viscosity fit-range check",
                "DMA-inspired softening-regime classification",
                "storage-modulus drop ratio and strength classification",
                "thermal diffusivity and thermal diffusion time scales",
                "cell thermal time-step ratio",
                "heating time across softening and melting intervals",
                "Stefan number",
                "phase-change energy-density and power-density scale",
                "source-term stiffness risk",
                "recommended first-pass time step",
                "Fluent hints and solver-plan patch integration",
                "no Fluent launch, UDF generation, or phase-change solver claim",
            ],
            "entrypoint": "fromcad2cfd fastcfd wax-rheology-handoff-demo",
        },
        "wax_rheology_phase_change_fluent_hints": {
            "status": "implemented_h4",
            "checks": [
                "energy equation recommendation",
                "temperature-dependent or Arrhenius viscosity recommendation",
                "phase-change source-term review",
                "source ramping, clamp, and NaN guard controls",
                "temperature, viscosity, energy-balance, and phase-change monitor recommendations",
                "reviewer checklist and explicit no-Fluent boundary",
            ],
            "entrypoint": "fromcad2cfd fastcfd validate-wax-rheology-phase-change",
        },
        "wax_rheology_phase_change_solver_plan_patch": {
            "status": "implemented_h4",
            "checks": [
                "schema auto-detection by compile-fluent-patch",
                "evidence-backed material-model patches",
                "evidence-backed source-term control patches",
                "evidence-backed transient time-step patch",
                "temperature and viscosity monitor patches",
                "postprocessing output requirements",
                "existing solver_plan_patch validator compatibility",
            ],
            "entrypoint": "fromcad2cfd fastcfd compile-fluent-patch --input <wax_passport.json> --output <solver_plan_patch.json>",
        },
    },
    "allowed_case_templates": {name: case.to_dict() for name, case in CASE_REGISTRY.items()},
    "lattice_sets": list(LATTICE_REGISTRY),
    "collision_models": list(COLLISION_REGISTRY),
    "safe_backends": ["mock", "fastfluent", "unstructured_fvm"],
    "physics_model_families": {
        "single_phase_laminar": {
            "status": "implemented",
            "role": "Current structured and unstructured pilot-flow validation routes.",
        },
        "vof_two_phase": {
            "status": "passport_and_setup_hints_implemented",
            "role": "Agent-safe VOF physics validation and Fluent setup guidance before any production multiphase run.",
        },
        "turbulence_models": {
            "status": "passport_hints_turbulence_ladder_and_channel_solves_implemented",
            "role": "RANS/SST/near-wall setup validation plus bounded algebraic eddy-viscosity, standard k-epsilon, pressure-corrected k-epsilon, Menter k-omega SST, and turbulence-ladder channel evidence; not a production turbulence solver.",
        },
        "non_newtonian_rheology": {
            "status": "passport_and_shear_rate_benchmark_implemented",
            "role": "Material-model validation and shear-rate evidence before Fluent non-Newtonian setup.",
        },
        "steam_air_condensation": {
            "status": "passport_hints_and_solver_plan_patch_implemented",
            "role": "Steam-air wall-condensation setup readiness and Fluent-facing handoff evidence; not a high-fidelity condensation solver.",
        },
        "wax_rheology_phase_change": {
            "status": "passport_hints_and_solver_plan_patch_implemented_h4",
            "role": "Wax material characterization, thermal softening, Arrhenius viscosity, latent heat, and phase-change readiness evidence before Fluent setup.",
        },
        "practical_native_utilities": {
            "status": "implemented_s2",
            "role": "Small native heat, scalar, material-property, source-term, sweep, and wax-application computations that provide practical screening evidence without Fluent.",
        },
        "practical_native_setup": {
            "status": "implemented_s3",
            "role": "Geometry-independent setup utilities for public native geometry manifests, boundary-condition contracts, initial fields, and practical case templates.",
        },
    },
    "backend_families": {
        "structured_lbm": {
            "status": "implemented_for_controlled_templates",
            "role": "Fast pilot simulations on bounded structured/block-structured LBM templates.",
        },
        "unstructured_fvm": {
            "status": "physics_extended_benchmarking_u0_u30",
            "role": "Engineering CAD-oriented unstructured finite-volume backend scaffold; current gates import meshes, audit them, validate boundary contracts, write finite-volume geometry operators, run 2D triangle and 3D tetra scalar diffusion, manufactured Stokes, pressure-projection, iterative flow benchmarks, boundary-aware Poiseuille channel validation, channel convergence evidence, VOF-lite alpha transport, simplified algebraic eddy-viscosity turbulent channel, bounded standard k-epsilon turbulent channel, pressure-corrected k-epsilon channel, bounded Menter k-omega SST channel benchmarks, JSON case-runner dispatch, controlled steady incompressible pressure-correction cases, and a public benchmark-suite evidence comparison through controlled methods.",
        },
    },
    "disabled_capabilities": [
        "arbitrary_shell",
        "arbitrary_python",
        "arbitrary_cpp_generation",
        "arbitrary_fastfluent_case_path",
        "raw_solver_source_edit_from_mcp",
        "validation_bypass_from_mcp",
        "unbounded_parameter_sweep",
        "unstructured_flow_solver_without_mesh_quality_gate",
        "vof_solver_claim",
        "turbulence_solver_claim",
        "non_newtonian_solver_claim",
        "vof_lite_solver_claim",
        "fluent_case_editing_from_hint_compiler",
        "fluent_execution_from_patch_compiler",
        "raw_fluent_patch_command",
    ],
}


def capability_inventory() -> dict[str, Any]:
    return dict(CAPABILITY_REGISTRY)


def capability_markdown() -> str:
    lines = [
        "# FastCFD Capability Inventory",
        "",
        f"Status: `{CAPABILITY_REGISTRY['status']}`",
        f"Role: {CAPABILITY_REGISTRY['role']}",
        "",
        "## Validation Gates",
        "",
    ]
    for name, info in CAPABILITY_REGISTRY["validation_gates"].items():
        lines.extend(
            [
                f"### `{name}`",
                "",
                f"- Status: `{info['status']}`",
                f"- Entrypoint: `{info['entrypoint']}`",
                f"- Checks: `{', '.join(info['checks'])}`",
                "",
            ]
        )
    lines.extend(
        [
            "## Allowed Case Templates",
            "",
        ]
    )
    for name, info in CAPABILITY_REGISTRY["allowed_case_templates"].items():
        lines.extend(
            [
                f"### `{name}`",
                "",
                f"- Status: `{info['status']}`",
                f"- Source asset: `{info['source_asset']}`",
                f"- Lattice: `{info['lattice']}`",
                f"- Boundaries: `{', '.join(info['boundaries'])}`",
                f"- Outputs: `{', '.join(info['outputs'])}`",
                "",
            ]
        )
    lines.extend(["## Physics Model Families", ""])
    for name, info in CAPABILITY_REGISTRY["physics_model_families"].items():
        lines.extend(
            [
                f"### `{name}`",
                "",
                f"- Status: `{info['status']}`",
                f"- Role: {info['role']}",
                "",
            ]
        )
    lines.extend(["## Disabled Capabilities", ""])
    lines.extend(f"- `{item}`" for item in CAPABILITY_REGISTRY["disabled_capabilities"])
    lines.append("")
    return "\n".join(lines)


def require_case_template(case_type: str) -> dict[str, Any]:
    try:
        return CAPABILITY_REGISTRY["allowed_case_templates"][case_type]
    except KeyError as exc:
        raise ValueError(f"Unsupported FastCFD case template: {case_type}") from exc
