"""Flow Pack adapter that connects CaseSpec, mesh, boundary, and material evidence."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from .boundary.boundary_contract import boundary_contract_markdown, validate_boundary_contract
from .core.case_spec import explain_case_spec_markdown, read_case_spec, validate_case_spec
from .core.claim_ledger import build_default_claim_ledger
from .core.evidence_bundle import summarize_evidence_bundle_markdown, validate_evidence_bundle
from .file_io import copy_file, ensure_dir, path_is_file, read_json_file, write_json_file, write_text_file
from .materials.material_contract import material_contract_markdown, validate_material_contract
from .mesh.mesh_gateway import generate_structured_mesh_demo, inspect_mesh_gateway


FLOW_PACK_SCHEMA_VERSION = "fastfluent_flow_pack_v1"
FLOW_PACK_VALIDATION_SCHEMA_VERSION = "fastfluent_flow_pack_validation_v1"


def build_flow_pack(
    case_file: str | Path,
    *,
    output_dir: str | Path,
    mesh_file: str | Path | None = None,
    mesh_mode: str = "auto",
    required_patches: tuple[str, ...] | None = None,
) -> dict[str, Any]:
    """Build a setup-only Flow Pack from a CaseSpec v3 document."""

    root = Path(output_dir)
    ensure_dir(root)
    case_path = Path(case_file)
    case_payload = read_case_spec(case_path)
    case_validation = validate_case_spec(case_payload)

    zones = _case_zone_names(case_payload)
    boundary_report = validate_boundary_contract(_object_or_empty(case_payload.get("boundary_conditions")), zones=zones)
    material_report = validate_material_contract(_object_or_empty(case_payload.get("materials")))
    mesh_result = _build_mesh_evidence(
        case_payload,
        root=root,
        mesh_file=mesh_file,
        mesh_mode=mesh_mode,
        required_patches=required_patches,
    )
    alignment_warnings = _mesh_boundary_alignment_warnings(case_payload, mesh_result)
    readiness = _build_readiness_gate(
        case_validation=case_validation.to_dict(),
        boundary_report=boundary_report,
        material_report=material_report,
        mesh_result=mesh_result,
        alignment_warnings=alignment_warnings,
    )
    artifacts = _write_flow_pack_artifacts(
        root=root,
        case_payload=case_payload,
        case_validation=case_validation.to_dict(),
        boundary_report=boundary_report,
        material_report=material_report,
        mesh_result=mesh_result,
        readiness=readiness,
    )
    flow_pack = {
        "schema_version": FLOW_PACK_SCHEMA_VERSION,
        "status": readiness["status"],
        "case_id": case_payload.get("case_id"),
        "case_type": case_payload.get("case_type"),
        "claim_level": "setup_only",
        "source_case_file": str(case_path),
        "solver_execution": "not_attempted",
        "contracts": {
            "case_spec": case_validation.to_dict(),
            "boundary_contract": boundary_report,
            "material_contract": material_report,
            "mesh_gateway": _compact_mesh_status(mesh_result),
        },
        "readiness_gate": readiness,
        "artifacts": artifacts,
        "limitations": [
            "Flow Pack v1 validates setup evidence only.",
            "No FastFluent solver, Fluent solver, PyFluent session, UDF, or case edit is executed.",
            "Native or Fluent-aligned evidence must be generated by downstream controlled routes.",
        ],
    }
    _write_json(root / "flow_pack.json", flow_pack)
    _write_json(root / "flow_pack_status.json", {"schema_version": "fastfluent_flow_pack_status_v1", "status": readiness["status"], "artifacts": artifacts})
    _write_text(root / "flow_pack_report.md", flow_pack_markdown(flow_pack))
    return flow_pack


def validate_flow_pack(flow_pack_dir: str | Path) -> dict[str, Any]:
    """Validate a Flow Pack output directory."""

    root = Path(flow_pack_dir)
    errors: list[str] = []
    warnings: list[str] = []
    flow_pack_path = root / "flow_pack.json"
    if not path_is_file(flow_pack_path):
        return {
            "schema_version": FLOW_PACK_VALIDATION_SCHEMA_VERSION,
            "status": "failed",
            "passed": False,
            "errors": ["flow_pack.json is missing."],
            "warnings": [],
        }
    try:
        flow_pack = read_json_file(flow_pack_path)
    except json.JSONDecodeError as exc:
        return {
            "schema_version": FLOW_PACK_VALIDATION_SCHEMA_VERSION,
            "status": "failed",
            "passed": False,
            "errors": [f"flow_pack.json is invalid JSON: {exc}"],
            "warnings": [],
        }
    if flow_pack.get("schema_version") != FLOW_PACK_SCHEMA_VERSION:
        errors.append(f"Unsupported schema_version: {flow_pack.get('schema_version')!r}")
    readiness = flow_pack.get("readiness_gate")
    if not isinstance(readiness, dict):
        errors.append("readiness_gate must be an object.")
    elif readiness.get("status") not in {"success", "partial", "failed"}:
        errors.append("readiness_gate.status must be success, partial, or failed.")
    artifacts = flow_pack.get("artifacts")
    if not isinstance(artifacts, dict):
        errors.append("artifacts must be an object.")
        artifacts = {}
    for name in _required_flow_pack_artifact_names():
        path_text = artifacts.get(name)
        if not isinstance(path_text, str) or not path_is_file(path_text):
            errors.append(f"Required artifact is missing: {name}")
    if flow_pack.get("solver_execution") != "not_attempted":
        errors.append("Flow Pack v1 must not claim solver execution.")
    if flow_pack.get("status") == "partial":
        warnings.append("Flow Pack is partial; downstream solver setup should be manually reviewed.")
    status = "failed" if errors else "passed"
    return {
        "schema_version": FLOW_PACK_VALIDATION_SCHEMA_VERSION,
        "status": status,
        "passed": status == "passed",
        "flow_pack_status": flow_pack.get("status"),
        "case_id": flow_pack.get("case_id"),
        "errors": errors,
        "warnings": warnings,
        "artifacts_checked": _required_flow_pack_artifact_names(),
    }


def export_flow_pack_evidence_bundle(
    flow_pack_dir: str | Path,
    *,
    output_dir: str | Path | None = None,
) -> dict[str, Any]:
    """Export a setup-only EvidenceBundle v3 from a Flow Pack."""

    flow_root = Path(flow_pack_dir)
    flow_pack_path = flow_root / "flow_pack.json"
    flow_pack = read_json_file(flow_pack_path)
    case_payload = _read_json(flow_root / "case.json")
    bundle_root = Path(output_dir) if output_dir else flow_root / "evidence_bundle"
    ensure_dir(bundle_root)

    validation = validate_flow_pack(flow_root)
    qoi_targets = case_payload.get("qoi_targets") if isinstance(case_payload.get("qoi_targets"), list) else []
    _write_json(bundle_root / "case.json", case_payload)
    _write_json(
        bundle_root / "run_manifest.json",
        {
            "schema_version": "fastfluent_run_manifest_v1",
            "status": "not_executed",
            "execution_mode": "setup_only",
            "source_flow_pack": str(flow_pack_path),
            "solver_execution": "not_attempted",
        },
    )
    _write_json(
        bundle_root / "validation_status.json",
        {
            "schema_version": "fastfluent_validation_status_v1",
            "status": "passed" if validation["passed"] else "failed",
            "flow_pack_validation": validation,
            "readiness_gate": flow_pack.get("readiness_gate", {}),
        },
    )
    _write_json(
        bundle_root / "qoi.json",
        {
            "schema_version": "fastfluent_qoi_v1",
            "status": "not_computed",
            "metrics": {},
            "qoi_targets": qoi_targets,
            "note": "Flow Pack export contains setup evidence only; no solver QoI has been computed.",
        },
    )
    _write_json(
        bundle_root / "claim_ledger.json",
        build_default_claim_ledger(
            claim_level="setup_only",
            supported_claims=[
                "The case setup, boundary-condition, material, and mesh-gateway artifacts are available for review."
            ],
            unsupported_claims=[
                "This bundle does not contain solver results.",
                "This bundle is not a production CFD validation result.",
                "This bundle does not replace Fluent setup review.",
            ],
            required_next_steps=[
                "Review Flow Pack readiness before selecting a native FastFluent or Fluent route.",
                "Run a controlled solver route before making physics or design claims.",
            ],
        ),
    )
    _write_text(
        bundle_root / "limitations.md",
        "# Limitations\n\n"
        "This EvidenceBundle was exported from Flow Pack v1 and contains setup-only evidence. "
        "No FastFluent or Fluent solver has been executed.\n",
    )
    _write_text(bundle_root / "report.md", _flow_pack_bundle_report(flow_pack, validation))
    _copy_optional_flow_pack_artifacts(flow_pack, bundle_root)
    bundle_validation = validate_evidence_bundle(bundle_root)
    _write_json(bundle_root / "evidence_bundle_validation.json", bundle_validation.to_dict())
    _write_text(
        bundle_root / "evidence_bundle_summary.md",
        summarize_evidence_bundle_markdown(bundle_root, bundle_validation),
    )
    return {
        "status": "success" if bundle_validation.passed else "failed",
        "operation": "export_flow_pack_evidence_bundle",
        "outputs": {
            "bundle_dir": str(bundle_root),
            "validation": bundle_validation.to_dict(),
            "artifacts": {
                "case": str(bundle_root / "case.json"),
                "run_manifest": str(bundle_root / "run_manifest.json"),
                "validation_status": str(bundle_root / "validation_status.json"),
                "qoi": str(bundle_root / "qoi.json"),
                "claim_ledger": str(bundle_root / "claim_ledger.json"),
                "limitations": str(bundle_root / "limitations.md"),
                "report": str(bundle_root / "report.md"),
                "evidence_bundle_validation": str(bundle_root / "evidence_bundle_validation.json"),
                "evidence_bundle_summary": str(bundle_root / "evidence_bundle_summary.md"),
            },
        },
        "errors": bundle_validation.missing_required_files + bundle_validation.json_errors,
    }


def flow_pack_markdown(flow_pack: dict[str, Any]) -> str:
    """Render a concise Flow Pack report."""

    readiness = flow_pack.get("readiness_gate", {})
    checks = readiness.get("checks", {})
    lines = [
        "# FastFluent Flow Pack v1",
        "",
        f"- Case ID: `{flow_pack.get('case_id')}`",
        f"- Case type: `{flow_pack.get('case_type')}`",
        f"- Status: `{flow_pack.get('status')}`",
        f"- Solver execution: `{flow_pack.get('solver_execution')}`",
        "",
        "## Readiness Checks",
        "",
    ]
    for name, passed in sorted(checks.items()):
        lines.append(f"- `{name}`: `{passed}`")
    lines.extend(["", "## Warnings", ""])
    warnings = readiness.get("warnings", [])
    lines.extend(f"- {item}" for item in warnings) if warnings else lines.append("- None")
    lines.extend(["", "## Errors", ""])
    errors = readiness.get("errors", [])
    lines.extend(f"- {item}" for item in errors) if errors else lines.append("- None")
    lines.extend(["", "## Next Actions", ""])
    actions = readiness.get("next_actions", [])
    lines.extend(f"- {item}" for item in actions) if actions else lines.append("- None")
    lines.extend(["", "## Limitations", ""])
    lines.extend(f"- {item}" for item in flow_pack.get("limitations", []))
    lines.append("")
    return "\n".join(lines)


def flow_pack_validation_markdown(validation: dict[str, Any]) -> str:
    """Render a Flow Pack validation result."""

    lines = [
        "# FastFluent Flow Pack Validation",
        "",
        f"- Status: `{validation.get('status')}`",
        f"- Case ID: `{validation.get('case_id')}`",
        f"- Flow Pack status: `{validation.get('flow_pack_status')}`",
        "",
        "## Warnings",
        "",
    ]
    warnings = validation.get("warnings", [])
    lines.extend(f"- {item}" for item in warnings) if warnings else lines.append("- None")
    lines.extend(["", "## Errors", ""])
    errors = validation.get("errors", [])
    lines.extend(f"- {item}" for item in errors) if errors else lines.append("- None")
    lines.append("")
    return "\n".join(lines)


def _build_mesh_evidence(
    case_payload: dict[str, Any],
    *,
    root: Path,
    mesh_file: str | Path | None,
    mesh_mode: str,
    required_patches: tuple[str, ...] | None,
) -> dict[str, Any]:
    mode = "gmsh" if mesh_file and mesh_mode == "auto" else mesh_mode
    if mode == "auto":
        mesh = _object_or_empty(case_payload.get("mesh"))
        mode = "structured-demo" if mesh.get("source") in {"structured", "analytic"} else "none"
    if mode == "structured-demo":
        geometry = _object_or_empty(case_payload.get("geometry"))
        mesh = _object_or_empty(case_payload.get("mesh"))
        parameters = _object_or_empty(geometry.get("parameters"))
        return generate_structured_mesh_demo(
            root / "mesh",
            nx=int(mesh.get("nx", 20)),
            ny=int(mesh.get("ny", 8)),
            length_m=float(parameters.get("length_m", 1.0)),
            height_m=float(parameters.get("height_m", 0.1)),
        )
    if mode == "gmsh":
        if not mesh_file:
            return {"status": "failed", "errors": ["mesh_file is required when mesh_mode is gmsh."], "outputs": {}}
        patches = required_patches or ("inlet", "outlet", "wall")
        return inspect_mesh_gateway(mesh_file, output_dir=root / "mesh", required_patches=patches)
    if mode == "none":
        return {
            "status": "skipped",
            "operation": "mesh_evidence_skipped",
            "message": "No mesh gateway evidence was generated.",
            "outputs": {},
            "errors": [],
        }
    return {"status": "failed", "errors": [f"Unsupported mesh_mode: {mesh_mode}"], "outputs": {}}


def _build_readiness_gate(
    *,
    case_validation: dict[str, Any],
    boundary_report: dict[str, Any],
    material_report: dict[str, Any],
    mesh_result: dict[str, Any],
    alignment_warnings: list[str],
) -> dict[str, Any]:
    checks = {
        "case_spec_passed": case_validation.get("status") == "passed",
        "boundary_contract_passed": boundary_report.get("status") == "passed",
        "material_contract_passed": material_report.get("status") == "passed",
        "mesh_gateway_available": mesh_result.get("status") == "success",
        "solver_not_attempted": True,
    }
    errors: list[str] = []
    warnings: list[str] = []
    if not checks["case_spec_passed"]:
        errors.extend(f"CaseSpec: {item}" for item in case_validation.get("errors", []))
    if not checks["boundary_contract_passed"]:
        errors.extend(f"Boundary: {item}" for item in boundary_report.get("errors", []))
    if not checks["material_contract_passed"]:
        errors.extend(f"Material: {item}" for item in material_report.get("errors", []))
    if mesh_result.get("status") == "failed":
        errors.extend(f"Mesh: {item}" for item in mesh_result.get("errors", []))
    elif mesh_result.get("status") != "success":
        warnings.append("Mesh gateway evidence is not available.")
    warnings.extend(case_validation.get("warnings", []))
    warnings.extend(boundary_report.get("warnings", []))
    warnings.extend(material_report.get("warnings", []))
    warnings.extend(alignment_warnings)
    if errors:
        status = "failed"
    elif all(checks.values()):
        status = "success"
    else:
        status = "partial"
    return {
        "schema_version": "fastfluent_flow_pack_readiness_gate_v1",
        "status": status,
        "ready_for_solver_setup": status == "success",
        "checks": checks,
        "errors": errors,
        "warnings": warnings,
        "next_actions": _next_actions_for_status(status),
    }


def _write_flow_pack_artifacts(
    *,
    root: Path,
    case_payload: dict[str, Any],
    case_validation: dict[str, Any],
    boundary_report: dict[str, Any],
    material_report: dict[str, Any],
    mesh_result: dict[str, Any],
    readiness: dict[str, Any],
) -> dict[str, str]:
    artifacts = {
        "case": str(root / "case.json"),
        "case_validation": str(root / "case_validation.json"),
        "case_summary": str(root / "case_summary.md"),
        "boundary_contract": str(root / "boundary_contract.json"),
        "boundary_validation": str(root / "boundary_validation.md"),
        "material_contract": str(root / "material_contract.json"),
        "material_model_report": str(root / "material_model_report.md"),
        "mesh_gateway_status": str(root / "mesh_status.json"),
        "readiness_gate": str(root / "readiness_gate.json"),
        "agent_next_actions": str(root / "agent_next_actions.json"),
        "fluent_hints": str(root / "fluent_hints.json"),
        "flow_pack": str(root / "flow_pack.json"),
        "flow_pack_report": str(root / "flow_pack_report.md"),
    }
    _write_json(root / "case.json", case_payload)
    _write_json(root / "case_validation.json", case_validation)
    _write_text(root / "case_summary.md", explain_case_spec_markdown(case_payload))
    _write_json(root / "boundary_contract.json", boundary_report)
    _write_text(root / "boundary_validation.md", boundary_contract_markdown(boundary_report))
    _write_json(root / "material_contract.json", material_report)
    _write_text(root / "material_model_report.md", material_contract_markdown(material_report))
    _write_json(root / "mesh_status.json", _compact_mesh_status(mesh_result))
    _copy_mesh_artifacts(mesh_result, artifacts)
    _write_json(root / "readiness_gate.json", readiness)
    _write_json(root / "agent_next_actions.json", {"schema_version": "fastfluent_agent_next_actions_v1", "actions": readiness["next_actions"]})
    _write_json(root / "fluent_hints.json", _flow_pack_fluent_hints(readiness))
    return artifacts


def _copy_mesh_artifacts(mesh_result: dict[str, Any], artifacts: dict[str, str]) -> None:
    mesh_artifacts = _object_or_empty(_object_or_empty(mesh_result.get("outputs")).get("artifacts"))
    mapping = {
        "mesh_manifest": "mesh_manifest.json",
        "mesh_quality": "mesh_quality.json",
        "fv_geometry": "fv_geometry.json",
        "mesh_vtu": "mesh.vtu",
    }
    for key, filename in mapping.items():
        source = mesh_artifacts.get(key)
        if isinstance(source, str) and path_is_file(source):
            target = Path(artifacts["case"]).parent / filename
            copy_file(source, target)
            artifacts[key] = str(target)


def _copy_optional_flow_pack_artifacts(flow_pack: dict[str, Any], bundle_root: Path) -> None:
    artifacts = _object_or_empty(flow_pack.get("artifacts"))
    mapping = {
        "mesh_manifest": "mesh_manifest.json",
        "mesh_quality": "mesh_quality.json",
        "boundary_contract": "boundary_contract.json",
        "material_contract": "material_contract.json",
        "fluent_hints": "fluent_hints.json",
    }
    for key, filename in mapping.items():
        source = artifacts.get(key)
        if isinstance(source, str) and path_is_file(source):
            copy_file(source, bundle_root / filename)
    case = _read_json(Path(artifacts.get("case", ""))) if isinstance(artifacts.get("case"), str) else {}
    if isinstance(case.get("numerics"), dict):
        _write_json(bundle_root / "numerics.json", case["numerics"])


def _mesh_boundary_alignment_warnings(case_payload: dict[str, Any], mesh_result: dict[str, Any]) -> list[str]:
    boundary_names = set(_object_or_empty(case_payload.get("boundary_conditions")))
    mesh_zones = set(_mesh_boundary_zone_names(mesh_result))
    if not boundary_names or not mesh_zones:
        return []
    missing = sorted(boundary_names - mesh_zones)
    if not missing:
        return []
    return ["Boundary conditions are not all present in mesh boundary zones: " + ", ".join(missing)]


def _mesh_boundary_zone_names(mesh_result: dict[str, Any]) -> list[str]:
    outputs = _object_or_empty(mesh_result.get("outputs"))
    manifest = _object_or_empty(outputs.get("manifest"))
    quality = _object_or_empty(outputs.get("quality"))
    for source in (manifest, quality):
        zone_counts = source.get("boundary_zone_counts")
        if isinstance(zone_counts, dict):
            return sorted(str(key) for key in zone_counts)
    return []


def _compact_mesh_status(mesh_result: dict[str, Any]) -> dict[str, Any]:
    outputs = _object_or_empty(mesh_result.get("outputs"))
    artifacts = _object_or_empty(outputs.get("artifacts"))
    return {
        "schema_version": "fastfluent_flow_pack_mesh_status_v1",
        "status": mesh_result.get("status"),
        "operation": mesh_result.get("operation"),
        "mesh_gateway_schema_version": outputs.get("mesh_gateway_schema_version"),
        "solver_execution": outputs.get("solver_execution", "not_attempted"),
        "artifacts": artifacts,
        "errors": mesh_result.get("errors", []),
    }


def _flow_pack_fluent_hints(readiness: dict[str, Any]) -> dict[str, Any]:
    return {
        "schema_version": "fastfluent_flow_pack_fluent_hints_v1",
        "status": readiness.get("status"),
        "hints": [
            {
                "category": "flow_pack",
                "recommendation": "Use this Flow Pack as reviewed setup evidence before selecting a controlled FastFluent or Fluent route.",
                "evidence": "flow_pack.json",
            },
            {
                "category": "solver_boundary",
                "recommendation": "Do not treat setup-only Flow Pack artifacts as solver QoI.",
                "evidence": "readiness_gate.json",
            },
        ],
        "limitations": ["This hint file does not edit or execute a Fluent case."],
    }


def _flow_pack_bundle_report(flow_pack: dict[str, Any], validation: dict[str, Any]) -> str:
    return (
        "# FastFluent Setup EvidenceBundle\n\n"
        f"- Source Flow Pack status: `{flow_pack.get('status')}`\n"
        f"- Flow Pack validation: `{validation.get('status')}`\n"
        f"- Case ID: `{flow_pack.get('case_id')}`\n"
        "- Solver execution: `not_attempted`\n\n"
        "This bundle contains setup evidence exported from Flow Pack v1. It is intended for agent review, "
        "route selection, and downstream controlled solver setup.\n"
    )


def _next_actions_for_status(status: str) -> list[str]:
    if status == "success":
        return [
            "Review the Flow Pack report.",
            "Choose a controlled native FastFluent route or export this pack for Fluent setup planning.",
            "Generate solver evidence only through an allowlisted route.",
        ]
    if status == "partial":
        return [
            "Add missing mesh-gateway evidence before solver setup.",
            "Review warnings before downstream handoff.",
        ]
    return [
        "Fix failed CaseSpec, boundary, material, or mesh checks before any solver setup.",
        "Rebuild the Flow Pack after corrections.",
    ]


def _required_flow_pack_artifact_names() -> list[str]:
    return [
        "case",
        "case_validation",
        "case_summary",
        "boundary_contract",
        "material_contract",
        "mesh_gateway_status",
        "readiness_gate",
        "agent_next_actions",
        "fluent_hints",
        "flow_pack",
        "flow_pack_report",
    ]


def _case_zone_names(payload: dict[str, Any]) -> list[str]:
    geometry = _object_or_empty(payload.get("geometry"))
    zones = geometry.get("zones", [])
    names: list[str] = []
    if isinstance(zones, list):
        for zone in zones:
            if isinstance(zone, str):
                names.append(zone)
            elif isinstance(zone, dict) and isinstance(zone.get("name"), str):
                names.append(zone["name"])
    return names


def _object_or_empty(value: Any) -> dict[str, Any]:
    return value if isinstance(value, dict) else {}


def _read_json(path: Path) -> dict[str, Any]:
    try:
        payload = read_json_file(path)
    except (OSError, json.JSONDecodeError):
        return {}
    return payload if isinstance(payload, dict) else {}


def _write_json(path: Path, payload: dict[str, Any]) -> Path:
    return write_json_file(path, payload)


def _write_text(path: Path, text: str) -> Path:
    return write_text_file(path, text)
