"""Controlled local HyperMesh batch adapter helpers."""

from __future__ import annotations

import json
import re
import subprocess
from pathlib import Path
from typing import Any

from .runtime import locate_hypermesh_runtime


GENERATED_SCRIPT_MARKER = "Generated by FromCAD2CFD"
SMOKE_BEGIN = "FROMCAD2CFD_HYPERMESH_SMOKE_BEGIN"
SMOKE_END = "FROMCAD2CFD_HYPERMESH_SMOKE_END"
TEMPLATE_BEGIN = "FROMCAD2CFD_HYPERMESH_MESHING_TEMPLATE_BEGIN"
TEMPLATE_END = "FROMCAD2CFD_HYPERMESH_MESHING_TEMPLATE_END"


def write_smoke_blockmesh_tcl(output_tcl: str | Path, hm_output: str | Path) -> dict[str, Any]:
    """Write a generated HyperMesh smoke script that creates a small meshed block."""

    output = Path(output_tcl)
    hm_path = Path(hm_output).resolve()
    output.parent.mkdir(parents=True, exist_ok=True)
    hm_text = _tcl_path(hm_path)
    text = "\n".join(
        [
            "# Generated by FromCAD2CFD. Controlled HyperMesh hmbatch smoke test.",
            f'puts "{SMOKE_BEGIN}"',
            f'set output_hm "{hm_text}"',
            '*collectorcreateonly components "block_wall" "" 7',
            "*createnode 0 0 0 0 0 0",
            "*surfacemode 4",
            "*createplane 1 0.0000 0.0000 1.0000 0.0000 0.0000 0.0000",
            "*surfaceplane 1 10",
            '*createmark surfaces 1 "displayed"',
            "*solid_extrude_from_surfs 1 0 0 5 1 2",
            "*setedgedensitylink 0",
            "*elementorder 1",
            '*createmark surfaces 1 "displayed"',
            "*interactiveremeshsurf 1 2 2 2 2 1 1",
            "*set_meshfaceparams 0 2 2 0 0 1 0.5 1 1",
            "*automesh 0 2 2",
            "*set_meshfaceparams 1 2 2 0 0 1 0.5 1 1",
            "*automesh 1 2 2",
            "*set_meshfaceparams 2 2 2 0 0 1 0.5 1 1",
            "*automesh 2 2 2",
            "*set_meshfaceparams 3 2 2 0 0 1 0.5 1 1",
            "*automesh 3 2 2",
            "*set_meshfaceparams 4 2 2 0 0 1 0.5 1 1",
            "*automesh 4 2 2",
            "*set_meshfaceparams 5 2 2 0 0 1 0.5 1 1",
            "*automesh 5 2 2",
            "*storemeshtodatabase 1",
            "*ameshclearsurface",
            '*writefile "$output_hm" 1',
            'puts "output_hm=$output_hm"',
            f'puts "{SMOKE_END}"',
            "exit",
            "",
        ]
    )
    output.write_text(text, encoding="utf-8")
    return {"status": "success", "script": str(output), "hm_output": str(hm_path)}


def run_hmbatch_script(
    script_path: str | Path,
    *,
    log_path: str | Path,
    manifest_path: str | Path | None = None,
    runtime_root: str | Path | None = None,
    timeout_s: int = 300,
) -> dict[str, Any]:
    """Run a generated HyperMesh Tcl script through hmbatch and write a manifest."""

    script = Path(script_path).resolve()
    log = Path(log_path).resolve()
    log.parent.mkdir(parents=True, exist_ok=True)
    if not script.exists():
        raise FileNotFoundError(script)
    _assert_generated_script(script)
    runtime = locate_hypermesh_runtime([str(runtime_root)] if runtime_root else None)
    best = runtime.get("best")
    if not best or not best.get("hmbatch"):
        result = {
            "status": "failed",
            "reason": "hmbatch_not_found",
            "script": str(script),
            "log": str(log),
            "runtime": runtime,
        }
        _write_manifest(manifest_path, result)
        return result
    command = [str(Path(str(best["hmbatch"])).resolve()), "-tcl", str(script)]
    completed = subprocess.run(
        command,
        cwd=str(script.parent),
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        timeout=timeout_s,
        check=False,
    )
    log.write_text(completed.stdout or "", encoding="utf-8")
    parsed = parse_hmbatch_log(log)
    result = {
        "status": "passed" if parsed["markers_ok"] and parsed["declared_outputs_ok"] else "failed",
        "process_exit_code": completed.returncode,
        "script": str(script),
        "log": str(log),
        "runtime": best,
        "command": command,
        "parsed_log": parsed,
    }
    _write_manifest(manifest_path, result)
    return result


def parse_hmbatch_log(log_path: str | Path) -> dict[str, Any]:
    """Parse FromCAD2CFD markers and declared output files from a hmbatch log."""

    log = Path(log_path)
    text = log.read_text(encoding="utf-8", errors="replace") if log.exists() else ""
    found_pairs = _marker_pairs(text)
    declared_outputs = _declared_outputs(text)
    output_checks = [
        {
            "path": path,
            "exists": Path(path).exists(),
            "size_bytes": Path(path).stat().st_size if Path(path).exists() else 0,
        }
        for path in declared_outputs
    ]
    return {
        "log": str(log),
        "markers": found_pairs,
        "markers_ok": bool(found_pairs) and all(item["complete"] for item in found_pairs),
        "declared_outputs": output_checks,
        "declared_outputs_ok": all(item["exists"] and item["size_bytes"] > 0 for item in output_checks)
        if output_checks
        else True,
        "hypermesh_version_seen": "Altair HyperMesh" in text,
        "raw_exit_code_warning": "HM exiting with code 1" in text,
    }


def _declared_outputs(text: str) -> list[str]:
    outputs: list[str] = []
    for line in text.splitlines():
        if line.startswith("output_hm="):
            outputs.append(line.split("=", 1)[1].strip())
    return outputs


def _marker_pairs(text: str) -> list[dict[str, Any]]:
    known = [
        (SMOKE_BEGIN, SMOKE_END),
        (TEMPLATE_BEGIN, TEMPLATE_END),
    ]
    pairs: dict[str, dict[str, Any]] = {}
    for begin, end in known:
        if begin in text or end in text:
            pairs[begin] = {"begin": begin, "end": end, "complete": begin in text and end in text}
    for match in re.finditer(r"(FROMCAD2CFD_HYPERMESH_[A-Z0-9_]+)_(BEGIN|END)", text):
        prefix = match.group(1)
        begin = f"{prefix}_BEGIN"
        end = f"{prefix}_END"
        pairs[begin] = {"begin": begin, "end": end, "complete": begin in text and end in text}
    return list(pairs.values())


def _assert_generated_script(script: Path) -> None:
    text = script.read_text(encoding="utf-8", errors="replace")
    if GENERATED_SCRIPT_MARKER not in text and "FROMCAD2CFD_HYPERMESH_" not in text:
        raise ValueError("Refusing to run a script that is not marked as generated by FromCAD2CFD.")
    blocked = ["exec ", "powershell", "cmd.exe", "Remove-Item", "del "]
    lowered = text.lower()
    for item in blocked:
        if item.lower() in lowered:
            raise ValueError(f"Refusing to run generated script with blocked token: {item}")


def _write_manifest(manifest_path: str | Path | None, payload: dict[str, Any]) -> None:
    if not manifest_path:
        return
    target = Path(manifest_path)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(json.dumps(payload, ensure_ascii=True, indent=2) + "\n", encoding="utf-8")


def _tcl_path(path: Path) -> str:
    return str(path).replace("\\", "/")
