"""Controlled local HyperMesh batch adapter helpers."""

from __future__ import annotations

import json
import re
import subprocess
from pathlib import Path
from typing import Any

from .runtime import locate_hypermesh_runtime


GENERATED_SCRIPT_MARKER = "Generated by FromCAD2CFD"
SMOKE_BEGIN = "FROMCAD2CFD_HYPERMESH_SMOKE_BEGIN"
SMOKE_END = "FROMCAD2CFD_HYPERMESH_SMOKE_END"
TEMPLATE_BEGIN = "FROMCAD2CFD_HYPERMESH_MESHING_TEMPLATE_BEGIN"
TEMPLATE_END = "FROMCAD2CFD_HYPERMESH_MESHING_TEMPLATE_END"
SURFACE_PIPELINE_BEGIN = "FROMCAD2CFD_HYPERMESH_SURFACE_PIPELINE_BEGIN"
SURFACE_PIPELINE_END = "FROMCAD2CFD_HYPERMESH_SURFACE_PIPELINE_END"


def write_smoke_blockmesh_tcl(output_tcl: str | Path, hm_output: str | Path) -> dict[str, Any]:
    """Write a generated HyperMesh smoke script that creates a small meshed block."""

    output = Path(output_tcl)
    hm_path = Path(hm_output).resolve()
    output.parent.mkdir(parents=True, exist_ok=True)
    hm_text = _tcl_path(hm_path)
    text = "\n".join(
        [
            "# Generated by FromCAD2CFD. Controlled HyperMesh hmbatch smoke test.",
            f'puts "{SMOKE_BEGIN}"',
            f'set output_hm "{hm_text}"',
            '*collectorcreateonly components "block_wall" "" 7',
            "*createnode 0 0 0 0 0 0",
            "*surfacemode 4",
            "*createplane 1 0.0000 0.0000 1.0000 0.0000 0.0000 0.0000",
            "*surfaceplane 1 10",
            '*createmark surfaces 1 "displayed"',
            "*solid_extrude_from_surfs 1 0 0 5 1 2",
            "*setedgedensitylink 0",
            "*elementorder 1",
            '*createmark surfaces 1 "displayed"',
            "*interactiveremeshsurf 1 2 2 2 2 1 1",
            "*set_meshfaceparams 0 2 2 0 0 1 0.5 1 1",
            "*automesh 0 2 2",
            "*set_meshfaceparams 1 2 2 0 0 1 0.5 1 1",
            "*automesh 1 2 2",
            "*set_meshfaceparams 2 2 2 0 0 1 0.5 1 1",
            "*automesh 2 2 2",
            "*set_meshfaceparams 3 2 2 0 0 1 0.5 1 1",
            "*automesh 3 2 2",
            "*set_meshfaceparams 4 2 2 0 0 1 0.5 1 1",
            "*automesh 4 2 2",
            "*set_meshfaceparams 5 2 2 0 0 1 0.5 1 1",
            "*automesh 5 2 2",
            "*storemeshtodatabase 1",
            "*ameshclearsurface",
            '*writefile "$output_hm" 1',
            'puts "output_hm=$output_hm"',
            f'puts "{SMOKE_END}"',
            "exit",
            "",
        ]
    )
    output.write_text(text, encoding="utf-8")
    return {"status": "success", "script": str(output), "hm_output": str(hm_path)}


def write_surface_mesh_tcl(
    output_tcl: str | Path,
    *,
    geometry_input: str | Path,
    hm_output: str | Path,
    target_size_m: float,
) -> dict[str, Any]:
    """Write a controlled HyperMesh Tcl script for 2D surface meshing only.

    The generated script imports CAD geometry, records entity counts and bounding boxes,
    creates a first-order surface mesh, saves the HyperMesh model, and exits. It does
    not create tetra, prism, hexcore, or any other 3D volume mesh.
    """

    if target_size_m <= 0:
        raise ValueError("target_size_m must be positive.")
    output = Path(output_tcl)
    geom_path = Path(geometry_input).resolve()
    hm_path = Path(hm_output).resolve()
    output.parent.mkdir(parents=True, exist_ok=True)
    geom_text = _tcl_path(geom_path)
    hm_text = _tcl_path(hm_path)
    mesh_size_text = f"{target_size_m:.12g}"
    text = "\n".join(
        [
            "# Generated by FromCAD2CFD. Controlled HyperMesh 2D surface-mesh pipeline.",
            "# This script intentionally does not create a HyperMesh 3D volume mesh.",
            f'puts "{SURFACE_PIPELINE_BEGIN}"',
            f'set input_geom "{geom_text}"',
            f'set output_hm "{hm_text}"',
            f"set mesh_size {mesh_size_text}",
            'puts "input_geom=$input_geom"',
            'puts "output_hm_target=$output_hm"',
            'puts "mesh_size_m=$mesh_size"',
            'if {[catch {eval *geomimport {"parasolid_parasolid"} {"$input_geom"}} import_err]} {',
            '    puts "import_status=failed"',
            '    puts "import_error=$import_err"',
            f'    puts "{SURFACE_PIPELINE_END}"',
            "    exit",
            "} else {",
            '    puts "import_status=passed"',
            "}",
            'foreach entity {comps solids surfaces lines} {',
            "    if {[catch {",
            '        *createmark $entity 1 "all"',
            "        set count [hm_marklength $entity 1]",
            "        set bbox [hm_getboundingbox $entity 1 0 0 0]",
            "    } err]} {",
            '        puts "${entity}_bbox_error=$err"',
            "    } else {",
            '        puts "${entity}_count=$count"',
            '        puts "${entity}_bbox=$bbox"',
            "        if {[llength $bbox] == 6} {",
            "            set dx [expr {[lindex $bbox 3] - [lindex $bbox 0]}]",
            "            set dy [expr {[lindex $bbox 4] - [lindex $bbox 1]}]",
            "            set dz [expr {[lindex $bbox 5] - [lindex $bbox 2]}]",
            '            puts "${entity}_extent=$dx $dy $dz"',
            "        }",
            "    }",
            "}",
            "*surfacemode 1",
            "*elementorder 1",
            "*setedgedensitylink 0",
            '*createmark surfaces 1 "all"',
            "set surface_count [hm_marklength surfaces 1]",
            'puts "surface_count_before=$surface_count"',
            "set face_errors 0",
            "if {$surface_count > 0} {",
            "    if {[catch {*interactiveremeshsurf 1 $mesh_size 2 2 1 0 1} remesh_err]} {",
            '        puts "interactiveremesh_status=failed"',
            '        puts "interactiveremesh_error=$remesh_err"',
            "    } else {",
            '        puts "interactiveremesh_status=passed"',
            "        for {set face_index 0} {$face_index < $surface_count} {incr face_index} {",
            "            if {[catch {*set_meshfaceparams $face_index 1 2 0 0 0 0.1 0 1} face_err]} {",
            "                incr face_errors",
            "            }",
            "            if {[catch {*automesh $face_index 5 2} auto_err]} {",
            "                incr face_errors",
            "            }",
            "        }",
            '        puts "face_error_count=$face_errors"',
            "        if {[catch {*storemeshtodatabase 0} store_err]} {",
            '            puts "store_surface_mesh_status=failed"',
            '            puts "store_surface_mesh_error=$store_err"',
            "        } else {",
            '            puts "store_surface_mesh_status=passed"',
            "        }",
            "        catch {*ameshclearsurface}",
            "    }",
            "}",
            '*createmark elems 1 "all"',
            'puts "element_count_after_surface_mesh=[hm_marklength elems 1]"',
            '*createmark nodes 1 "all"',
            'puts "node_count_after_surface_mesh=[hm_marklength nodes 1]"',
            '*createmark elems 1 "all"',
            '*createmark elems 2',
            'if {[catch {*elementtestduplicates elems 1 2 2} duplicate_err]} {',
            '    puts "duplicate_check_status=failed"',
            '    puts "duplicate_check_error=$duplicate_err"',
            "} else {",
            '    puts "duplicate_check_status=passed"',
            "    set duplicate_count_before_cleanup [hm_marklength elems 2]",
            '    puts "duplicate_element_count_before_cleanup=$duplicate_count_before_cleanup"',
            "    if {$duplicate_count_before_cleanup > 0} {",
            "        if {[catch {*deletemark elems 2} delete_dup_err]} {",
            '            puts "duplicate_cleanup_status=failed"',
            '            puts "duplicate_cleanup_error=$delete_dup_err"',
            "        } else {",
            '            puts "duplicate_cleanup_status=passed"',
            "        }",
            "    } else {",
            '        puts "duplicate_cleanup_status=not_needed"',
            "    }",
            '    *createmark elems 1 "all"',
            "    *createmark elems 2",
            "    if {[catch {*elementtestduplicates elems 1 2 2} duplicate_recheck_err]} {",
            '        puts "duplicate_recheck_status=failed"',
            '        puts "duplicate_recheck_error=$duplicate_recheck_err"',
            "    } else {",
            '        puts "duplicate_recheck_status=passed"',
            '        puts "duplicate_element_count=[hm_marklength elems 2]"',
            "    }",
            "}",
            'if {[catch {*writefile "$output_hm" 1} write_err]} {',
            '    puts "write_status=failed"',
            '    puts "write_error=$write_err"',
            "} else {",
            '    puts "write_status=passed"',
            '    puts "output_hm=$output_hm"',
            "}",
            f'puts "{SURFACE_PIPELINE_END}"',
            "exit",
            "",
        ]
    )
    output.write_text(text, encoding="utf-8")
    return {
        "status": "success",
        "script": str(output),
        "geometry_input": str(geom_path),
        "hm_output": str(hm_path),
        "target_size_m": target_size_m,
    }


def run_hmbatch_script(
    script_path: str | Path,
    *,
    log_path: str | Path,
    manifest_path: str | Path | None = None,
    runtime_root: str | Path | None = None,
    timeout_s: int = 300,
) -> dict[str, Any]:
    """Run a generated HyperMesh Tcl script through hmbatch and write a manifest."""

    script = Path(script_path).resolve()
    log = Path(log_path).resolve()
    log.parent.mkdir(parents=True, exist_ok=True)
    if not script.exists():
        raise FileNotFoundError(script)
    _assert_generated_script(script)
    runtime = locate_hypermesh_runtime([str(runtime_root)] if runtime_root else None)
    best = runtime.get("best")
    if not best or not best.get("hmbatch"):
        result = {
            "status": "failed",
            "reason": "hmbatch_not_found",
            "script": str(script),
            "log": str(log),
            "runtime": runtime,
        }
        _write_manifest(manifest_path, result)
        return result
    command = [str(Path(str(best["hmbatch"])).resolve()), "-tcl", str(script)]
    completed = subprocess.run(
        command,
        cwd=str(script.parent),
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        timeout=timeout_s,
        check=False,
    )
    log.write_text(completed.stdout or "", encoding="utf-8")
    parsed = parse_hmbatch_log(log)
    result = {
        "status": "passed" if parsed["markers_ok"] and parsed["declared_outputs_ok"] else "failed",
        "process_exit_code": completed.returncode,
        "script": str(script),
        "log": str(log),
        "runtime": best,
        "command": command,
        "parsed_log": parsed,
    }
    _write_manifest(manifest_path, result)
    return result


def parse_hmbatch_log(log_path: str | Path) -> dict[str, Any]:
    """Parse FromCAD2CFD markers and declared output files from a hmbatch log."""

    log = Path(log_path)
    text = log.read_text(encoding="utf-8", errors="replace") if log.exists() else ""
    found_pairs = _marker_pairs(text)
    declared_outputs = _declared_outputs(text)
    output_checks = [
        {
            "path": path,
            "exists": Path(path).exists(),
            "size_bytes": Path(path).stat().st_size if Path(path).exists() else 0,
        }
        for path in declared_outputs
    ]
    return {
        "log": str(log),
        "markers": found_pairs,
        "markers_ok": bool(found_pairs) and all(item["complete"] for item in found_pairs),
        "declared_outputs": output_checks,
        "declared_outputs_ok": all(item["exists"] and item["size_bytes"] > 0 for item in output_checks)
        if output_checks
        else True,
        "hypermesh_version_seen": "Altair HyperMesh" in text,
        "raw_exit_code_warning": "HM exiting with code 1" in text,
    }


def parse_surface_mesh_log(log_path: str | Path) -> dict[str, Any]:
    """Parse a controlled HyperMesh surface-mesh pipeline log into metrics."""

    base = parse_hmbatch_log(log_path)
    log = Path(log_path)
    text = log.read_text(encoding="utf-8", errors="replace") if log.exists() else ""
    metrics = _key_value_metrics(text)
    result: dict[str, Any] = {
        "status": _surface_status(base, metrics),
        "log": str(log),
        "base_log": base,
        "metrics": metrics,
        "checks": {
            "markers_ok": base["markers_ok"],
            "declared_outputs_ok": base["declared_outputs_ok"],
            "import_passed": metrics.get("import_status") == "passed",
            "surface_mesh_stored": metrics.get("store_surface_mesh_status") == "passed",
            "write_passed": metrics.get("write_status") == "passed",
            "no_face_errors": metrics.get("face_error_count", 1) == 0,
            "no_duplicate_elements": metrics.get("duplicate_element_count", 0) == 0,
            "elements_created": metrics.get("element_count_after_surface_mesh", 0) > 0,
            "nodes_created": metrics.get("node_count_after_surface_mesh", 0) > 0,
        },
        "notes": [
            "HyperMesh process exit code 1 can still be acceptable when FromCAD2CFD markers and declared outputs pass.",
            "This parser covers 2D surface mesh generation only; it does not validate a 3D volume mesh.",
        ],
    }
    return result


def write_surface_mesh_reports(
    log_path: str | Path,
    *,
    json_report: str | Path | None = None,
    markdown_report: str | Path | None = None,
) -> dict[str, Any]:
    """Parse a surface-mesh log and optionally write JSON and Markdown reports."""

    result = parse_surface_mesh_log(log_path)
    if json_report:
        target = Path(json_report)
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(json.dumps(result, ensure_ascii=True, indent=2) + "\n", encoding="utf-8")
        result["json_report"] = str(target)
    if markdown_report:
        target = Path(markdown_report)
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(_surface_report_markdown(result), encoding="utf-8")
        result["markdown_report"] = str(target)
    return result


def _declared_outputs(text: str) -> list[str]:
    outputs: list[str] = []
    for line in text.splitlines():
        if line.startswith("output_hm="):
            outputs.append(line.split("=", 1)[1].strip())
    return outputs


def _marker_pairs(text: str) -> list[dict[str, Any]]:
    known = [
        (SMOKE_BEGIN, SMOKE_END),
        (TEMPLATE_BEGIN, TEMPLATE_END),
    ]
    pairs: dict[str, dict[str, Any]] = {}
    for begin, end in known:
        if begin in text or end in text:
            pairs[begin] = {"begin": begin, "end": end, "complete": begin in text and end in text}
    for match in re.finditer(r"(FROMCAD2CFD_HYPERMESH_[A-Z0-9_]+)_(BEGIN|END)", text):
        prefix = match.group(1)
        begin = f"{prefix}_BEGIN"
        end = f"{prefix}_END"
        pairs[begin] = {"begin": begin, "end": end, "complete": begin in text and end in text}
    return list(pairs.values())


def _key_value_metrics(text: str) -> dict[str, Any]:
    metrics: dict[str, Any] = {}
    prefixes = (
        "input_geom=",
        "output_hm_target=",
        "mesh_size_m=",
        "import_status=",
        "import_error=",
        "comps_count=",
        "solids_count=",
        "surfaces_count=",
        "lines_count=",
        "comps_bbox=",
        "solids_bbox=",
        "surfaces_bbox=",
        "lines_bbox=",
        "comps_extent=",
        "solids_extent=",
        "surfaces_extent=",
        "lines_extent=",
        "surface_count_before=",
        "interactiveremesh_status=",
        "interactiveremesh_error=",
        "face_error_count=",
        "store_surface_mesh_status=",
        "store_surface_mesh_error=",
        "element_count_after_surface_mesh=",
        "node_count_after_surface_mesh=",
        "duplicate_check_status=",
        "duplicate_check_error=",
        "duplicate_element_count_before_cleanup=",
        "duplicate_cleanup_status=",
        "duplicate_cleanup_error=",
        "duplicate_recheck_status=",
        "duplicate_recheck_error=",
        "duplicate_element_count=",
        "write_status=",
        "write_error=",
        "output_hm=",
    )
    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line or "=" not in line:
            continue
        if not line.startswith(prefixes):
            continue
        key, value = line.split("=", 1)
        metrics[key] = _parse_metric_value(value.strip())
    return metrics


def _parse_metric_value(value: str) -> Any:
    if " " in value and not any(sep in value for sep in ("/", "\\")):
        parts = value.split()
        parsed = [_parse_metric_value(part) for part in parts]
        if all(isinstance(item, int | float) for item in parsed):
            return parsed
    try:
        if re.fullmatch(r"[-+]?\d+", value):
            return int(value)
        if re.fullmatch(r"[-+]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][-+]?\d+)?", value):
            return float(value)
    except ValueError:
        pass
    return value


def _surface_status(base: dict[str, Any], metrics: dict[str, Any]) -> str:
    required = [
        base["markers_ok"],
        base["declared_outputs_ok"],
        metrics.get("import_status") == "passed",
        metrics.get("store_surface_mesh_status") == "passed",
        metrics.get("write_status") == "passed",
        metrics.get("element_count_after_surface_mesh", 0) > 0,
        metrics.get("node_count_after_surface_mesh", 0) > 0,
    ]
    if (
        all(required)
        and metrics.get("face_error_count", 1) == 0
        and metrics.get("duplicate_element_count", 0) == 0
    ):
        return "passed"
    if all(required):
        return "review"
    return "failed"


def _surface_report_markdown(result: dict[str, Any]) -> str:
    metrics = result["metrics"]
    checks = result["checks"]
    lines = [
        "# HyperMesh Surface Mesh Report",
        "",
        f"- Status: `{result['status']}`",
        f"- Log: `{result['log']}`",
        f"- Geometry input: `{metrics.get('input_geom', '')}`",
        f"- HyperMesh output: `{metrics.get('output_hm', metrics.get('output_hm_target', ''))}`",
        f"- Target surface size: `{metrics.get('mesh_size_m', '')}` m",
        "",
        "## Geometry",
        "",
        f"- Components: `{metrics.get('comps_count', '')}`",
        f"- Solids: `{metrics.get('solids_count', '')}`",
        f"- Surfaces: `{metrics.get('surfaces_count', '')}`",
        f"- Lines: `{metrics.get('lines_count', '')}`",
        f"- Surface extent: `{metrics.get('surfaces_extent', '')}`",
        "",
        "## Surface Mesh",
        "",
        f"- Surface count before mesh: `{metrics.get('surface_count_before', '')}`",
        f"- Face error count: `{metrics.get('face_error_count', '')}`",
        f"- Surface element count: `{metrics.get('element_count_after_surface_mesh', '')}`",
        f"- Node count: `{metrics.get('node_count_after_surface_mesh', '')}`",
        f"- Duplicate elements before cleanup: `{metrics.get('duplicate_element_count_before_cleanup', '')}`",
        f"- Duplicate cleanup status: `{metrics.get('duplicate_cleanup_status', '')}`",
        f"- Duplicate element count: `{metrics.get('duplicate_element_count', '')}`",
        "",
        "## Checks",
        "",
    ]
    lines.extend(f"- {key}: `{value}`" for key, value in checks.items())
    lines.extend(
        [
            "",
            "## Boundary",
            "",
            "This report is for HyperMesh 2D surface meshing only. The pipeline intentionally does not create a HyperMesh 3D volume mesh.",
            "",
        ]
    )
    return "\n".join(lines)


def _assert_generated_script(script: Path) -> None:
    text = script.read_text(encoding="utf-8", errors="replace")
    if GENERATED_SCRIPT_MARKER not in text and "FROMCAD2CFD_HYPERMESH_" not in text:
        raise ValueError("Refusing to run a script that is not marked as generated by FromCAD2CFD.")
    blocked = ["exec ", "powershell", "cmd.exe", "Remove-Item", "del "]
    lowered = text.lower()
    for item in blocked:
        if item.lower() in lowered:
            raise ValueError(f"Refusing to run generated script with blocked token: {item}")


def _write_manifest(manifest_path: str | Path | None, payload: dict[str, Any]) -> None:
    if not manifest_path:
        return
    target = Path(manifest_path)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(json.dumps(payload, ensure_ascii=True, indent=2) + "\n", encoding="utf-8")


def _tcl_path(path: Path) -> str:
    return str(path).replace("\\", "/")
