"""Public-safe HyperMesh CFD meshing plan validation and templates."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any


MESHING_PLAN_SCHEMA_VERSION = "fromcad2cfd_hypermesh_surface_meshing_plan_v1"

ALLOWED_BOUNDARY_TYPES = {"inlet", "outlet", "wall", "symmetry", "interface", "farfield"}
ALLOWED_EXPORT_FORMATS = {"hypermesh_hm", "fluent_surface_msh"}


def read_json(path: str | Path) -> dict[str, Any]:
    return json.loads(Path(path).read_text(encoding="utf-8"))


def write_json(path: str | Path, payload: dict[str, Any]) -> None:
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(json.dumps(payload, ensure_ascii=True, indent=2) + "\n", encoding="utf-8")


def validate_meshing_plan(payload: dict[str, Any], *, public_mode: bool = True) -> dict[str, Any]:
    """Validate a public-safe HyperMesh CFD surface-meshing plan."""

    errors: list[str] = []
    warnings: list[str] = []
    if payload.get("schema_version") != MESHING_PLAN_SCHEMA_VERSION:
        errors.append(f"schema_version must be {MESHING_PLAN_SCHEMA_VERSION}.")
    for key in (
        "plan_name",
        "geometry_input",
        "hypermesh_model_output",
        "surface_mesh_output",
        "units",
        "boundaries",
        "surface_mesh",
        "quality",
    ):
        if key not in payload:
            errors.append(f"Missing required key: {key}.")

    for key in ("geometry_input", "hypermesh_model_output", "surface_mesh_output"):
        if key in payload:
            _validate_public_path(str(payload[key]), key, public_mode, errors)

    _validate_units(payload.get("units"), errors)
    _validate_boundaries(payload.get("boundaries"), errors, warnings)
    _validate_surface_mesh(payload.get("surface_mesh"), errors)
    _warn_ignored_3d_controls(payload, warnings)
    _validate_quality(payload.get("quality"), errors, warnings)
    _validate_export(payload.get("export", {}), errors)

    return {
        "status": "passed" if not errors else "failed",
        "schema_version": MESHING_PLAN_SCHEMA_VERSION,
        "plan_name": payload.get("plan_name"),
        "public_mode": public_mode,
        "errors": errors,
        "warnings": warnings,
        "boundary_count": len(payload.get("boundaries", {})) if isinstance(payload.get("boundaries"), dict) else 0,
    }


def hypermesh_python_template(plan: dict[str, Any]) -> str:
    """Generate an advisory HyperMesh CFD surface-meshing Python template from a validated plan."""

    validation = validate_meshing_plan(plan, public_mode=False)
    if validation["status"] != "passed":
        raise ValueError("Invalid HyperMesh meshing plan: " + "; ".join(validation["errors"]))
    plan_json = json.dumps(plan, ensure_ascii=True, indent=4)
    return "\n".join(
        [
            "# Generated by FromCAD2CFD. Review inside a licensed HyperMesh CFD environment.",
            "# This template is adapter-ready: replace TODO blocks with recorded HyperMesh Python API calls.",
            "from pathlib import Path",
            "import json",
            "",
            "try:",
            "    import hm",
            "    import hw",
            "except Exception as exc:",
            "    raise RuntimeError('This script must run inside HyperMesh / HyperWorks Python.') from exc",
            "",
            f"PLAN = json.loads({plan_json!r})",
            "RUN_DIR = Path(PLAN.get('run_directory', 'sandbox/output/hypermesh_meshing_run'))",
            "RUN_DIR.mkdir(parents=True, exist_ok=True)",
            "",
            "def main():",
            "    # TODO: create or obtain the active HyperMesh model/session.",
            "    # TODO: import PLAN['geometry_input'] with unit handling.",
            "    # TODO: create CFD boundary components using PLAN['boundaries'].",
            "    # TODO: inspect the imported bounding box and convert PLAN['surface_mesh'] sizes to model units.",
            "    # TODO: create only the 2D surface mesh; do not create tetra/prism/hex volume mesh in HyperMesh.",
            "    # TODO: run surface quality checks from PLAN['quality'].",
            "    # TODO: write PLAN['hypermesh_model_output'] and PLAN['surface_mesh_output'].",
            "    manifest = RUN_DIR / 'hypermesh_meshing_manifest.json'",
            "    manifest.write_text(json.dumps({'status': 'template_only', 'plan_name': PLAN['plan_name']}, indent=2), encoding='utf-8')",
            "",
            "if __name__ == '__main__':",
            "    main()",
            "",
        ]
    )


def hypermesh_tcl_template(plan: dict[str, Any]) -> str:
    """Generate an advisory HyperMesh surface-meshing Tcl template from a validated plan."""

    validation = validate_meshing_plan(plan, public_mode=False)
    if validation["status"] != "passed":
        raise ValueError("Invalid HyperMesh meshing plan: " + "; ".join(validation["errors"]))
    escaped_plan = json.dumps(plan, ensure_ascii=True).replace("\\", "\\\\").replace('"', '\\"')
    return "\n".join(
        [
            "# Generated by FromCAD2CFD. Review before running with hmbatch.",
            "# Prefer a recorded HyperMesh CFD workflow for production commands.",
            'puts "FROMCAD2CFD_HYPERMESH_MESHING_TEMPLATE_BEGIN"',
            f'set plan_json "{escaped_plan}"',
            'puts "plan_name=' + str(plan["plan_name"]) + '"',
            "# TODO: hm_answernext yes",
            "# TODO: import geometry, create components, assign CFD zones.",
            "# TODO: inspect bounding box and convert mesh sizes to model units.",
            "# TODO: create only the 2D surface mesh; no HyperMesh volume mesh.",
            "# TODO: surface quality check and surface mesh export.",
            'puts "template_status=template_only"',
            'puts "FROMCAD2CFD_HYPERMESH_MESHING_TEMPLATE_END"',
            "exit",
            "",
        ]
    )


def _validate_units(units: Any, errors: list[str]) -> None:
    if not isinstance(units, dict):
        errors.append("units must be an object.")
        return
    if not isinstance(units.get("length_unit"), str):
        errors.append("units.length_unit must be a string such as mm or m.")
    if _positive_float(units.get("scale_to_m")) is None:
        errors.append("units.scale_to_m must be positive.")


def _validate_boundaries(boundaries: Any, errors: list[str], warnings: list[str]) -> None:
    if not isinstance(boundaries, dict) or not boundaries:
        errors.append("boundaries must be a non-empty object keyed by Fluent zone name.")
        return
    seen_types: set[str] = set()
    for name, boundary in boundaries.items():
        if not isinstance(boundary, dict):
            errors.append(f"boundary {name} must be an object.")
            continue
        boundary_type = boundary.get("type")
        if boundary_type not in ALLOWED_BOUNDARY_TYPES:
            errors.append(f"boundary {name}.type must be one of: {', '.join(sorted(ALLOWED_BOUNDARY_TYPES))}.")
        else:
            seen_types.add(str(boundary_type))
        if "selector" not in boundary and "description" not in boundary:
            warnings.append(f"boundary {name} has no selector or description; recorded scripts may need manual mapping.")
    if "inlet" not in seen_types:
        warnings.append("No inlet boundary was declared.")
    if "outlet" not in seen_types:
        warnings.append("No outlet boundary was declared.")


def _validate_surface_mesh(surface_mesh: Any, errors: list[str]) -> None:
    if not isinstance(surface_mesh, dict):
        errors.append("surface_mesh must be an object.")
        return
    if _positive_float(surface_mesh.get("target_size_mm")) is None:
        errors.append("surface_mesh.target_size_mm must be positive.")
    for key in ("min_size_mm", "max_size_mm"):
        if key in surface_mesh and _positive_float(surface_mesh.get(key)) is None:
            errors.append(f"surface_mesh.{key} must be positive when provided.")


def _warn_ignored_3d_controls(payload: dict[str, Any], warnings: list[str]) -> None:
    for key in ("boundary_layer", "volume_mesh"):
        if key in payload:
            warnings.append(f"{key} is ignored by the HyperMesh surface-only adapter.")


def _validate_quality(quality: Any, errors: list[str], warnings: list[str]) -> None:
    if not isinstance(quality, dict):
        errors.append("quality must be an object.")
        return
    if _positive_float(quality.get("max_skewness")) is None:
        errors.append("quality.max_skewness must be positive.")
    if _positive_float(quality.get("max_aspect_ratio")) is None:
        errors.append("quality.max_aspect_ratio must be positive.")
    if "max_skewness" in quality and _positive_float(quality.get("max_skewness")):
        if float(quality["max_skewness"]) > 0.95:
            warnings.append("quality.max_skewness is loose for Fluent CFD; tighten if convergence is sensitive.")


def _validate_export(export: Any, errors: list[str]) -> None:
    if not export:
        return
    if not isinstance(export, dict):
        errors.append("export must be an object.")
        return
    if export.get("format") not in ALLOWED_EXPORT_FORMATS:
        errors.append(f"export.format must be one of: {', '.join(sorted(ALLOWED_EXPORT_FORMATS))}.")


def _validate_public_path(path_value: str, field: str, public_mode: bool, errors: list[str]) -> None:
    path = Path(path_value)
    if public_mode and path.is_absolute():
        errors.append(f"{field} must be a relative public path, not an absolute local path.")
    text = path_value.replace("\\", "/").lower()
    private_markers = ["d:/cyk2", "d:\\cyk2", "program files/altair", "program files\\altair", "license"]
    if public_mode and any(marker in text for marker in private_markers):
        errors.append(f"{field} contains a private or local-system path marker.")


def _positive_float(value: Any) -> float | None:
    try:
        result = float(value)
    except (TypeError, ValueError):
        return None
    return result if result > 0 else None


def _positive_int(value: Any) -> int | None:
    try:
        result = int(value)
    except (TypeError, ValueError):
        return None
    return result if result > 0 else None
