from __future__ import annotations

from pathlib import Path

import pytest

from fromcad2cfd_hypermesh_meshing.adapter import parse_hmbatch_log, write_smoke_blockmesh_tcl
from fromcad2cfd_hypermesh_meshing.runtime import locate_hypermesh_runtime
from fromcad2cfd_hypermesh_meshing.schemas import (
    MESHING_PLAN_SCHEMA_VERSION,
    hypermesh_python_template,
    hypermesh_tcl_template,
    validate_meshing_plan,
)
from fromcad2cfd_mcp_hypermesh_meshing.server import server_descriptor


def _valid_plan() -> dict[str, object]:
    return {
        "schema_version": MESHING_PLAN_SCHEMA_VERSION,
        "plan_name": "unit_hypermesh_plan",
        "geometry_input": "sandbox/input/unit.step",
        "hypermesh_model_output": "sandbox/output/unit.hm",
        "fluent_mesh_output": "sandbox/output/unit.msh",
        "units": {"length_unit": "mm", "scale_to_m": 0.001},
        "boundaries": {
            "inlet": {"type": "inlet", "description": "inlet face"},
            "outlet": {"type": "outlet", "description": "outlet face"},
            "outer_wall": {"type": "wall", "description": "outer wall"},
            "model_wall": {"type": "wall", "description": "model wall"},
        },
        "surface_mesh": {"target_size_mm": 5.0, "min_size_mm": 1.0},
        "boundary_layer": {"enabled": True, "first_height_mm": 0.1, "layers": 5, "growth_rate": 1.2},
        "volume_mesh": {"method": "hybrid_prism_tetra", "target_size_mm": 8.0},
        "quality": {"max_skewness": 0.9, "max_aspect_ratio": 20.0},
        "export": {"format": "fluent_msh"},
    }


def test_validate_hypermesh_meshing_plan_passes() -> None:
    result = validate_meshing_plan(_valid_plan())

    assert result["status"] == "passed"
    assert result["boundary_count"] == 4


def test_validate_hypermesh_meshing_plan_rejects_absolute_public_path() -> None:
    plan = _valid_plan()
    plan["geometry_input"] = str(Path.cwd() / "sandbox" / "input" / "unit.step")

    result = validate_meshing_plan(plan)

    assert result["status"] == "failed"
    assert any("geometry_input" in item for item in result["errors"])


def test_hypermesh_templates_include_plan_name() -> None:
    plan = _valid_plan()

    python_text = hypermesh_python_template(plan)
    tcl_text = hypermesh_tcl_template(plan)

    assert "unit_hypermesh_plan" in python_text
    assert "unit_hypermesh_plan" in tcl_text
    assert "template_only" in python_text
    assert "template_only" in tcl_text


def test_runtime_discovery_accepts_missing_extra_root() -> None:
    result = locate_hypermesh_runtime(["sandbox/missing_altair_root"])

    assert result["status"] in {"found", "not_found"}
    assert "candidates" in result


def test_mcp_descriptor_lists_safe_hypermesh_tools() -> None:
    descriptor = server_descriptor()

    assert descriptor["name"] == "fromcad2cfd-hypermesh-meshing"
    assert "fromcad2cfd_hypermesh_meshing_validate_plan" in descriptor["allowed_tools"]
    assert "execute_tcl" in descriptor["disabled_tools"]


def test_write_smoke_tcl_contains_generated_marker(tmp_path: Path) -> None:
    script = tmp_path / "smoke.tcl"
    hm_output = tmp_path / "smoke.hm"

    result = write_smoke_blockmesh_tcl(script, hm_output)

    text = script.read_text(encoding="utf-8")
    assert result["status"] == "success"
    assert "Generated by FromCAD2CFD" in text
    assert "FROMCAD2CFD_HYPERMESH_SMOKE_BEGIN" in text
    assert str(hm_output.resolve()).replace("\\", "/") in text


def test_parse_hmbatch_log_uses_markers_and_outputs(tmp_path: Path) -> None:
    hm_output = tmp_path / "smoke.hm"
    hm_output.write_text("placeholder", encoding="utf-8")
    log = tmp_path / "smoke.log"
    log.write_text(
        "\n".join(
            [
                "FROMCAD2CFD_HYPERMESH_SMOKE_BEGIN",
                f"output_hm={str(hm_output).replace(chr(92), '/')}",
                "FROMCAD2CFD_HYPERMESH_SMOKE_END",
                "Altair HyperMesh v2024.0.0.26",
                "HM exiting with code 1",
            ]
        ),
        encoding="utf-8",
    )

    result = parse_hmbatch_log(log)

    assert result["markers_ok"] is True
    assert result["declared_outputs_ok"] is True
    assert result["hypermesh_version_seen"] is True
    assert result["raw_exit_code_warning"] is True


def test_parse_hmbatch_log_accepts_generic_workflow_markers(tmp_path: Path) -> None:
    hm_output = tmp_path / "front300_import_only.hm"
    hm_output.write_text("placeholder", encoding="utf-8")
    log = tmp_path / "front300_import.log"
    log.write_text(
        "\n".join(
            [
                "FROMCAD2CFD_HYPERMESH_IMPORT_BEGIN",
                "import_status=passed",
                f"output_hm={str(hm_output).replace(chr(92), '/')}",
                "FROMCAD2CFD_HYPERMESH_IMPORT_END",
                "Altair HyperMesh v2024.0.0.26",
                "HM exiting with code 1",
            ]
        ),
        encoding="utf-8",
    )

    result = parse_hmbatch_log(log)

    assert result["markers_ok"] is True
    assert result["declared_outputs_ok"] is True
    assert result["markers"] == [
        {
            "begin": "FROMCAD2CFD_HYPERMESH_IMPORT_BEGIN",
            "end": "FROMCAD2CFD_HYPERMESH_IMPORT_END",
            "complete": True,
        }
    ]


def test_parse_hmbatch_log_fails_missing_output(tmp_path: Path) -> None:
    log = tmp_path / "smoke.log"
    log.write_text(
        "\n".join(
            [
                "FROMCAD2CFD_HYPERMESH_SMOKE_BEGIN",
                f"output_hm={str(tmp_path / 'missing.hm').replace(chr(92), '/')}",
                "FROMCAD2CFD_HYPERMESH_SMOKE_END",
            ]
        ),
        encoding="utf-8",
    )

    result = parse_hmbatch_log(log)

    assert result["markers_ok"] is True
    assert result["declared_outputs_ok"] is False


def test_run_guard_rejects_unmarked_script(tmp_path: Path) -> None:
    from fromcad2cfd_hypermesh_meshing.adapter import run_hmbatch_script

    script = tmp_path / "unsafe.tcl"
    script.write_text('puts "hello"\n', encoding="utf-8")

    with pytest.raises(ValueError):
        run_hmbatch_script(script, log_path=tmp_path / "unsafe.log")
