name: Syntax

on:
  push:
  pull_request:

jobs:
  compile:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Compile source
        run: python -m compileall src
